# Parsing/emission failures must not overwrite either previously generated output.
set(_directory "${BINARY_DIR}/generator-failures")
file(MAKE_DIRECTORY "${_directory}")
set(_cases Metadata Private BitField RefQualifier PrivateFunction PrivateBase)
set(_Metadata "STRUCT(NAME(\"bad\")) struct Bad { PROPERTY(META(\"Key\", 1), META(\"Key\", 2)) int Value; };")
set(_Private "CLASS() class Bad { PROPERTY() int Value; };")
set(_BitField "STRUCT() struct Bad { PROPERTY() unsigned Value : 1; };")
set(_RefQualifier "CLASS() class Bad { public: FUNCTION() void Run() & {} };")
set(_PrivateFunction "CLASS() class Bad { FUNCTION() void Run() {} };")
set(_PrivateBase "struct Parent {}; CLASS() class Bad : private Parent {};")
set(_Metadata_expected "Duplicate metadata key")
set(_Private_expected "Non-public property requires REFLECT_BODY")
set(_BitField_expected "Unsupported bit-field/reference/volatile property")
set(_RefQualifier_expected "RefQualifiedMember")
set(_PrivateFunction_expected "Non-public function requires REFLECT_BODY")
set(_PrivateBase_expected "Only public inheritance is supported")
foreach(_case IN LISTS _cases)
    set(_header "${_directory}/${_case}.h")
    set(_input "${_directory}/${_case}.cpp")
    set(_output "${_directory}/${_case}.gen.cpp")
    set(_generated_header "${_directory}/${_case}.gen.h")
    file(WRITE "${_header}" "#include <reflection_entt/Annotations.h>\n#define NAME(value) META(\"Name\", value)\n${_${_case}}\n")
    file(WRITE "${_input}" "#include \"${_header}\"\n")
    file(WRITE "${_output}" "cpp sentinel")
    file(WRITE "${_generated_header}" "header sentinel")
    execute_process(COMMAND "${GENERATOR}" --module Failure --header "${_header}" --output "${_output}"
        "${_input}" -- -std=c++20 "-I${SOURCE_DIR}/include" "-resource-dir=${RESOURCE_DIR}"
        RESULT_VARIABLE _result OUTPUT_VARIABLE _stdout ERROR_VARIABLE _stderr)
    if(_result EQUAL 0)
        message(FATAL_ERROR "${_case}: generator incorrectly succeeded")
    endif()
    string(FIND "${_stderr}" "${_${_case}_expected}" _diagnostic_position)
    if(_diagnostic_position LESS 0)
        message(FATAL_ERROR "${_case}: failed for an unexpected reason: ${_stderr}")
    endif()
    file(READ "${_output}" _cpp)
    file(READ "${_generated_header}" _header_text)
    if(NOT _cpp STREQUAL "cpp sentinel" OR NOT _header_text STREQUAL "header sentinel")
        message(FATAL_ERROR "${_case}: failed generation replaced old outputs")
    endif()
endforeach()
