#pragma once

#include "Base.h"
#include "EnumBit.h"
#include "Reflection/ReflectionMacro.h"

BEGIN(Engine)

#define MAX_RENDER_TARGET_COUNT 8

#define MAX_GLOBAL_CONSTANT_SLOTS 1
#define MAX_OBJECT_CONSTANT_SLOTS 1
#define MAX_PASS_CONSTANT_SLOTS 2
#define MAX_CONSTANT_BUFFER_SLOTS (MAX_GLOBAL_CONSTANT_SLOTS + MAX_OBJECT_CONSTANT_SLOTS + MAX_PASS_CONSTANT_SLOTS)

#define MAX_MATERIAL_TEXTURE_SLOTS 16
#define MAX_PASS_TEXTURE_SLOTS 16
#define MAX_TEXTURE_SLOTS (MAX_MATERIAL_TEXTURE_SLOTS + MAX_PASS_TEXTURE_SLOTS)

#define MAX_MATERIAL_SAMPLER_SLOTS 8
#define MAX_PASS_SAMPLER_SLOTS 8
#define MAX_SAMPLER_SLOTS (MAX_MATERIAL_SAMPLER_SLOTS + MAX_PASS_SAMPLER_SLOTS)

#define MAX_STORAGE_BUFFERS 8

#define MAX_BUFFER_SLOTS 4
#define MAX_SWAPCHAIN_BUFFERS 3

ENUM()
enum class ERenderTargetType : uint8
{
	Color,
	GBuffer,
	DepthStencil,
};

END