#pragma once
// Auto-generated by ReflectionGenerator.py
#include "Core/Public/Engine_Includes.h"
#include "Core/Public/Reflection/ReflectionMacro.h"
#include "Core/Public/Reflection/ContainerReflection.h"

// [헤더 파일 자동 포함]
#include "Components/Public/Component.h"
#include "Components/Public/Transfrom/Transform.h"
#include "Core/Public/Vertex.h"
#include "Scene/Public/GameObject.h"


namespace Engine {

// Struct: tagComponentDesc
BEGIN_REFLECT(tagComponentDesc)
    REFLECT_PROPERTY(Active, Engine::EPropertyType::Bool, "bool")
    REFLECT_PROPERTY(Tag, Engine::EPropertyType::String, "wstring")
    REFLECT_PROPERTY(Owner, Engine::EPropertyType::Object, "class GameObject")
END_REFLECT()

// Class: Component
BEGIN_REFLECT(Component)
    REFLECT_PROPERTY(m_Active, Engine::EPropertyType::Bool, "bool")
    REFLECT_PROPERTY(m_Tag, Engine::EPropertyType::String, "wstring")
    REFLECT_PROPERTY(m_Owner, Engine::EPropertyType::Object, "GameObject")
END_REFLECT()

// Struct: tagTransformDesc
BEGIN_REFLECT(tagTransformDesc)
    REFLECT_PROPERTY(Position, Engine::EPropertyType::Vector3, "vec3")
    REFLECT_PROPERTY(Rotation, Engine::EPropertyType::Vector3, "vec3")
    REFLECT_PROPERTY(Scale, Engine::EPropertyType::Vector3, "vec3")
END_REFLECT()

// Class: Transform
BEGIN_REFLECT(Transform)
    REFLECT_PROPERTY(m_Position, Engine::EPropertyType::Vector3, "vec3")
    REFLECT_PROPERTY(m_Rotation, Engine::EPropertyType::Quaternion, "quat")
    REFLECT_PROPERTY(m_Scale, Engine::EPropertyType::Vector3, "vec3")
    REFLECT_PROPERTY(m_LocalMatrix, Engine::EPropertyType::Struct, "mat4")
    REFLECT_PROPERTY(m_WorldMatrix, Engine::EPropertyType::Struct, "mat4")
    REFLECT_BITFLAG(m_Flags, Engine::EPropertyType::BitFlag, "ETransformFlag")
END_REFLECT()

// Struct: Vertex
BEGIN_REFLECT(Vertex)
    REFLECT_PROPERTY(position, Engine::EPropertyType::Vector3, "glm::vec3")
    REFLECT_PROPERTY(normal, Engine::EPropertyType::Vector3, "glm::vec3")
    REFLECT_PROPERTY(texCoord, Engine::EPropertyType::Vector2, "glm::vec2")
    REFLECT_PROPERTY(tangent, Engine::EPropertyType::Vector3, "glm::vec3")
    REFLECT_PROPERTY(bitangent, Engine::EPropertyType::Vector3, "glm::vec3")
    REFLECT_PROPERTY(color, Engine::EPropertyType::Vector4, "glm::vec4")
END_REFLECT()

// Class: GameObject
BEGIN_REFLECT(GameObject)
    REFLECT_SET(m_TagSet, unordered_set<wstring>, wstring, "wstring")
    REFLECT_PROPERTY(m_Name, Engine::EPropertyType::String, "wstring", "PROP_NAME")
    REFLECT_PROPERTY(m_ID, Engine::EPropertyType::UInt64, "uint64", READONLY)
    REFLECT_BITFLAG(m_Flags, Engine::EPropertyType::BitFlag, "EObjectFlag")
    REFLECT_PROPERTY(m_LayerIndex, Engine::EPropertyType::UInt32, "uint32", READONLY)
END_REFLECT()

}
