#pragma once
// Auto-generated by ReflectionGenerator.py
#include "Core/Public/Engine_Includes.h"
#include "Core/Public/Reflection/ReflectionMacro.h"
#include "Core/Public/Reflection/ContainerReflection.h"

// [헤더 파일 자동 포함]
#include "Components/Public/Camera/Camera.h"
#include "Components/Public/Component.h"
#include "Components/Public/Render/MeshRenderer/MeshRenderer.h"
#include "Components/Public/Render/RenderComponent.h"
#include "Components/Public/Render/SpriteRenderer/SpriteRenderer.h"
#include "Components/Public/Transfrom/Transform.h"
#include "Core/Public/Rect.h"
#include "Core/Public/Vertex.h"
#include "Renderer/Public/RHIDefinitions.h"
#include "Resource/Public/Material/Material.h"
#include "Resource/Public/Material/MaterialInstance.h"
#include "Resource/Public/Material/MaterialInterface.h"
#include "Resource/Public/Mesh/Mesh.h"
#include "Resource/Public/Resource.h"
#include "Resource/Public/Shader/Shader.h"
#include "Resource/Public/Sprite/Sprite.h"
#include "Resource/Public/Texture/Texture.h"
#include "Scene/Public/GameObject.h"


namespace Engine {

// [Explicit Initialization Function for Enums]
void InitEnumReflection()
{
// Enum: EDrawMode
BEGIN_ENUM_REFLECT(EDrawMode)
    REFLECT_ENUM_ENTRY(EDrawMode, Simple)
    REFLECT_ENUM_ENTRY(EDrawMode, Sliced)
    REFLECT_ENUM_ENTRY(EDrawMode, Tiled)
    REFLECT_ENUM_ENTRY(EDrawMode, Filled)
END_ENUM_REFLECT(EDrawMode)
// Enum: ETransformFlag
BEGIN_ENUM_REFLECT(ETransformFlag)
    REFLECT_ENUM_ENTRY(ETransformFlag, None)
    REFLECT_ENUM_ENTRY(ETransformFlag, InheritPosition)
    REFLECT_ENUM_ENTRY(ETransformFlag, InheritRotation)
    REFLECT_ENUM_ENTRY(ETransformFlag, InheritScale)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionX)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionY)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionZ)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockPosition)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationX)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationY)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationZ)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockRotation)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleX)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleY)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleZ)
    REFLECT_ENUM_ENTRY(ETransformFlag, LockScale)
    REFLECT_ENUM_ENTRY(ETransformFlag, Static)
    REFLECT_ENUM_ENTRY(ETransformFlag, AllInherit)
    REFLECT_ENUM_ENTRY(ETransformFlag, AllLocked)
    REFLECT_ENUM_ENTRY(ETransformFlag, Default)
END_ENUM_REFLECT(ETransformFlag)
// Enum: EPipelineType
BEGIN_ENUM_REFLECT(EPipelineType)
    REFLECT_ENUM_ENTRY(EPipelineType, Graphics)
    REFLECT_ENUM_ENTRY(EPipelineType, Compute)
END_ENUM_REFLECT(EPipelineType)
// Enum: EBlendMode
BEGIN_ENUM_REFLECT(EBlendMode)
    REFLECT_ENUM_ENTRY(EBlendMode, Opaque)
    REFLECT_ENUM_ENTRY(EBlendMode, AlphaBlend)
    REFLECT_ENUM_ENTRY(EBlendMode, Additive)
    REFLECT_ENUM_ENTRY(EBlendMode, NonPremultiplied)
    REFLECT_ENUM_ENTRY(EBlendMode, Masked)
END_ENUM_REFLECT(EBlendMode)
// Enum: EFillMode
BEGIN_ENUM_REFLECT(EFillMode)
    REFLECT_ENUM_ENTRY(EFillMode, Wireframe)
    REFLECT_ENUM_ENTRY(EFillMode, Solid)
END_ENUM_REFLECT(EFillMode)
// Enum: ECullMode
BEGIN_ENUM_REFLECT(ECullMode)
    REFLECT_ENUM_ENTRY(ECullMode, None)
    REFLECT_ENUM_ENTRY(ECullMode, Front)
    REFLECT_ENUM_ENTRY(ECullMode, Back)
END_ENUM_REFLECT(ECullMode)
// Enum: EFrontFace
BEGIN_ENUM_REFLECT(EFrontFace)
    REFLECT_ENUM_ENTRY(EFrontFace, Clockwise)
    REFLECT_ENUM_ENTRY(EFrontFace, CounterClockwise)
END_ENUM_REFLECT(EFrontFace)
// Enum: EDepthMode
BEGIN_ENUM_REFLECT(EDepthMode)
    REFLECT_ENUM_ENTRY(EDepthMode, None)
    REFLECT_ENUM_ENTRY(EDepthMode, ReadOnly)
    REFLECT_ENUM_ENTRY(EDepthMode, ReadWrite)
END_ENUM_REFLECT(EDepthMode)
// Enum: ETopology
BEGIN_ENUM_REFLECT(ETopology)
    REFLECT_ENUM_ENTRY(ETopology, TriangleList)
    REFLECT_ENUM_ENTRY(ETopology, TriangleStrip)
    REFLECT_ENUM_ENTRY(ETopology, LineList)
    REFLECT_ENUM_ENTRY(ETopology, LineStrip)
    REFLECT_ENUM_ENTRY(ETopology, PointList)
END_ENUM_REFLECT(ETopology)
// Enum: ECompareOp
BEGIN_ENUM_REFLECT(ECompareOp)
    REFLECT_ENUM_ENTRY(ECompareOp, Never)
    REFLECT_ENUM_ENTRY(ECompareOp, Less)
    REFLECT_ENUM_ENTRY(ECompareOp, Equal)
    REFLECT_ENUM_ENTRY(ECompareOp, LessOrEqual)
    REFLECT_ENUM_ENTRY(ECompareOp, Greater)
    REFLECT_ENUM_ENTRY(ECompareOp, NotEqual)
    REFLECT_ENUM_ENTRY(ECompareOp, GreaterOrEqual)
    REFLECT_ENUM_ENTRY(ECompareOp, Always)
END_ENUM_REFLECT(ECompareOp)
// Enum: EMaterialParameterType
BEGIN_ENUM_REFLECT(EMaterialParameterType)
    REFLECT_ENUM_ENTRY(EMaterialParameterType, Float)
    REFLECT_ENUM_ENTRY(EMaterialParameterType, Float2)
    REFLECT_ENUM_ENTRY(EMaterialParameterType, Float3)
    REFLECT_ENUM_ENTRY(EMaterialParameterType, Float4)
    REFLECT_ENUM_ENTRY(EMaterialParameterType, Int)
    REFLECT_ENUM_ENTRY(EMaterialParameterType, Bool)
    REFLECT_ENUM_ENTRY(EMaterialParameterType, Matrix)
END_ENUM_REFLECT(EMaterialParameterType)
// Enum: EObjectFlag
BEGIN_ENUM_REFLECT(EObjectFlag)
    REFLECT_ENUM_ENTRY(EObjectFlag, None)
    REFLECT_ENUM_ENTRY(EObjectFlag, Active)
    REFLECT_ENUM_ENTRY(EObjectFlag, Visible)
    REFLECT_ENUM_ENTRY(EObjectFlag, Paused)
    REFLECT_ENUM_ENTRY(EObjectFlag, Dead)
    REFLECT_ENUM_ENTRY(EObjectFlag, Default)
END_ENUM_REFLECT(EObjectFlag)

}

// [System Initialization Function]
// 이 함수를 엔진 초기화 단계에서 반드시 호출해야 모든 타입이 정상 등록됩니다.
void InitReflectionSystem()
{
	InitEnumReflection();
	REFLECT_STATIC_TYPE(tagComponentDesc);
	REFLECT_STATIC_TYPE(Component);
	REFLECT_STATIC_TYPE(Camera);
	REFLECT_STATIC_TYPE(RenderComponent);
	REFLECT_STATIC_TYPE(MeshRenderer);
	REFLECT_STATIC_TYPE(SpriteRenderer);
	REFLECT_STATIC_TYPE(tagTransformDesc);
	REFLECT_STATIC_TYPE(Transform);
	REFLECT_STATIC_TYPE(Rect);
	REFLECT_STATIC_TYPE(Vertex);
	REFLECT_STATIC_TYPE(Resource);
	REFLECT_STATIC_TYPE(Material);
	REFLECT_STATIC_TYPE(MaterialInstance);
	REFLECT_STATIC_TYPE(TextureSlot);
	REFLECT_STATIC_TYPE(MaterialParameter);
	REFLECT_STATIC_TYPE(MaterialInterface);
	REFLECT_STATIC_TYPE(Mesh);
	REFLECT_STATIC_TYPE(Shader);
	REFLECT_STATIC_TYPE(Sprite);
	REFLECT_STATIC_TYPE(Texture);
	REFLECT_STATIC_TYPE(GameObject);

}

// [Class/Struct Property Registration]

// Struct: tagComponentDesc
BEGIN_REFLECT(tagComponentDesc)
    REFLECT_PROPERTY(Active, Engine::EPropertyType::Bool, "bool")
    REFLECT_PROPERTY(Tag, Engine::EPropertyType::String, "wstring")
    REFLECT_PROPERTY(Owner, Engine::EPropertyType::Object, "class GameObject")
END_REFLECT()

// Class: Component
BEGIN_REFLECT(Component)
END_REFLECT()

// Class: Camera
BEGIN_REFLECT(Camera)
    REFLECT_PARENT(Component)
    REFLECT_PROPERTY(m_FOV, Engine::EPropertyType::F32, "f32", EDITCONDITION("m_IsPerspective"))
    REFLECT_PROPERTY(m_Near, Engine::EPropertyType::F32, "f32")
    REFLECT_PROPERTY(m_Far, Engine::EPropertyType::F32, "f32")
    REFLECT_PROPERTY(m_Aspect, Engine::EPropertyType::F32, "f32", EDITCONDITION("m_IsPerspective"))
    REFLECT_PROPERTY(m_Width, Engine::EPropertyType::F32, "f32", EDITCONDITION("!m_IsPerspective"))
    REFLECT_PROPERTY(m_Height, Engine::EPropertyType::F32, "f32", EDITCONDITION("!m_IsPerspective"))
    REFLECT_PROPERTY(m_IsPerspective, Engine::EPropertyType::Bool, "bool")
    REFLECT_PROPERTY(m_ProjMatrix, Engine::EPropertyType::Matrix4, "glm::mat4", READONLY)
    REFLECT_PROPERTY(m_ViewMatrix, Engine::EPropertyType::Matrix4, "glm::mat4", READONLY)
END_REFLECT()

// Class: RenderComponent
BEGIN_REFLECT(RenderComponent)
    REFLECT_PARENT(Component)
    REFLECT_PROPERTY(m_RenderPassID, Engine::EPropertyType::UInt32, "uint32", CATEGORY("PROP_INFORMATION"))
    REFLECT_VECTOR(m_MaterialInstances, vector<MaterialInstance*>, MaterialInstance*, "MaterialInstance*")
END_REFLECT()

// Class: MeshRenderer
BEGIN_REFLECT(MeshRenderer)
    REFLECT_PARENT(RenderComponent)
    REFLECT_PROPERTY(m_Mesh, Engine::EPropertyType::Object, "class Mesh", NAME(L"Mesh"))
END_REFLECT()

// Class: SpriteRenderer
BEGIN_REFLECT(SpriteRenderer)
    REFLECT_PARENT(RenderComponent)
    REFLECT_PROPERTY(m_Tiling, Engine::EPropertyType::Vector2, "vec2", DEFAULT(vec2(1.f, 1.f)))
    REFLECT_PROPERTY(m_Sprite, Engine::EPropertyType::Object, "Sprite")
    REFLECT_PROPERTY(m_CachedSpriteVersion, Engine::EPropertyType::UInt32, "uint32", CATEGORY("DETAIL"), READONLY)
    REFLECT_PROPERTY(m_DrawMode, Engine::EPropertyType::Enum, "EDrawMode")
END_REFLECT()

// Struct: tagTransformDesc
BEGIN_REFLECT(tagTransformDesc)
    REFLECT_PROPERTY(Position, Engine::EPropertyType::Vector3, "vec3")
    REFLECT_PROPERTY(Rotation, Engine::EPropertyType::Vector3, "vec3")
    REFLECT_PROPERTY(Scale, Engine::EPropertyType::Vector3, "vec3")
END_REFLECT()

// Class: Transform
BEGIN_REFLECT(Transform)
    REFLECT_PARENT(Component)
    REFLECT_PROPERTY(m_Position, Engine::EPropertyType::Vector3, "vec3")
    REFLECT_PROPERTY(m_Rotation, Engine::EPropertyType::Quaternion, "quat")
    REFLECT_PROPERTY(m_Scale, Engine::EPropertyType::Vector3, "vec3")
    REFLECT_PROPERTY(m_LocalMatrix, Engine::EPropertyType::Matrix4, "mat4", "PROP_LOCALMATRIX",READONLY)
    REFLECT_PROPERTY(m_WorldMatrix, Engine::EPropertyType::Matrix4, "mat4", "PROP_WORLDMATRIX", READONLY)
    REFLECT_BITFLAG(m_Flags, Engine::EPropertyType::BitFlag, "ETransformFlag", "PROP_BITFLAG")
END_REFLECT()

// Struct: Rect
BEGIN_REFLECT(Rect)
    REFLECT_PROPERTY(Left, Engine::EPropertyType::F32, "f32")
    REFLECT_PROPERTY(Top, Engine::EPropertyType::F32, "f32")
    REFLECT_PROPERTY(Width, Engine::EPropertyType::F32, "f32")
    REFLECT_PROPERTY(Height, Engine::EPropertyType::F32, "f32")
END_REFLECT()

// Struct: Vertex
BEGIN_REFLECT(Vertex)
    REFLECT_PROPERTY(position, Engine::EPropertyType::Vector3, "glm::vec3")
    REFLECT_PROPERTY(normal, Engine::EPropertyType::Vector3, "glm::vec3")
    REFLECT_PROPERTY(texCoord, Engine::EPropertyType::Vector2, "glm::vec2")
    REFLECT_PROPERTY(tangent, Engine::EPropertyType::Vector3, "glm::vec3")
    REFLECT_PROPERTY(bitangent, Engine::EPropertyType::Vector3, "glm::vec3")
    REFLECT_PROPERTY(color, Engine::EPropertyType::Vector4, "glm::vec4")
END_REFLECT()

// Class: Resource
BEGIN_REFLECT(Resource)
    REFLECT_PARENT(Base)
    REFLECT_PROPERTY(m_Tag, Engine::EPropertyType::String, "wstring")
    REFLECT_PROPERTY(m_Version, Engine::EPropertyType::UInt32, "uint32", READONLY)
END_REFLECT()

// Class: Material
BEGIN_REFLECT(Material)
    REFLECT_PARENT(MaterialInterface)
END_REFLECT()

// Class: MaterialInstance
BEGIN_REFLECT(MaterialInstance)
    REFLECT_PARENT(MaterialInterface)
    REFLECT_PROPERTY(m_BaseMaterial, Engine::EPropertyType::Object, "class Material")
END_REFLECT()

// Struct: TextureSlot
BEGIN_REFLECT(TextureSlot)
    REFLECT_PROPERTY(slot, Engine::EPropertyType::UInt32, "uint32")
    REFLECT_PROPERTY(texture, Engine::EPropertyType::Object, "RHITexture")
    REFLECT_PROPERTY(SamplerKey, Engine::EPropertyType::String, "wstring")
END_REFLECT()

// Struct: MaterialParameter
BEGIN_REFLECT(MaterialParameter)
    REFLECT_PROPERTY(type, Engine::EPropertyType::Enum, "EMaterialParameterType")
    REFLECT_VECTOR(data, vector<uint8>, uint8, "uint8")
END_REFLECT()

// Class: MaterialInterface
BEGIN_REFLECT(MaterialInterface)
    REFLECT_PARENT(Resource)
    REFLECT_PROPERTY(m_BlendMode, Engine::EPropertyType::Enum, "EBlendMode", CATEGORY(L"Pipeline"))
    REFLECT_PROPERTY(m_CullMode, Engine::EPropertyType::Enum, "ECullMode", CATEGORY(L"Pipeline"))
    REFLECT_PROPERTY(m_FillMode, Engine::EPropertyType::Enum, "EFillMode", CATEGORY(L"Pipeline"))
    REFLECT_PROPERTY(m_DepthMode, Engine::EPropertyType::Enum, "EDepthMode", CATEGORY(L"Pipeline"))
    REFLECT_PROPERTY(m_DepthCompareOp, Engine::EPropertyType::Enum, "ECompareOp", CATEGORY(L"Pipeline"))
    REFLECT_PROPERTY(m_VertexShader, Engine::EPropertyType::Object, "Shader")
    REFLECT_PROPERTY(m_PixelShader, Engine::EPropertyType::Object, "Shader")
    REFLECT_MAP(m_Parameters, "MaterialParameter", "string")
    REFLECT_MAP(m_TextureSlots, "TextureSlot", "string")
END_REFLECT()

// Class: Mesh
BEGIN_REFLECT(Mesh)
    REFLECT_PARENT(Resource)
    REFLECT_PROPERTY(m_Topology, Engine::EPropertyType::Enum, "ETopology", CATEGORY("PROP_INFORMATION"))
    REFLECT_PROPERTY(m_VertexCount, Engine::EPropertyType::UInt32, "uint32", CATEGORY("PROP_INFORMATION"), READONLY)
    REFLECT_PROPERTY(m_IndexCount, Engine::EPropertyType::UInt32, "uint32", CATEGORY("PROP_INFORMATION"), READONLY)
END_REFLECT()

// Class: Shader
BEGIN_REFLECT(Shader)
    REFLECT_PARENT(Resource)
    REFLECT_PROPERTY(m_RHIShader, Engine::EPropertyType::Object, "RHIShader")
END_REFLECT()

// Class: Sprite
BEGIN_REFLECT(Sprite)
    REFLECT_PARENT(Resource)
    REFLECT_PROPERTY(m_Texture, Engine::EPropertyType::Object, "Texture")
    REFLECT_PROPERTY(m_Region, Engine::EPropertyType::Struct, "Rect")
    REFLECT_PROPERTY(m_Pivot, Engine::EPropertyType::Vector2, "vec2", DEFAULT(vec2(0.5f, 0.5f)))
END_REFLECT()

// Class: Texture
BEGIN_REFLECT(Texture)
    REFLECT_PARENT(Resource)
    REFLECT_PROPERTY(m_PixelPerUnit, Engine::EPropertyType::F32, "f32")
    REFLECT_PROPERTY(m_Path, Engine::EPropertyType::String, "wstring", DIRECTORY, READONLY)
END_REFLECT()

// Class: GameObject
BEGIN_REFLECT(GameObject)
    REFLECT_PARENT(Base)
    REFLECT_PROPERTY(m_ID, Engine::EPropertyType::UInt64, "uint64", CATEGORY("PROP_INFORMATION"), READONLY)
    REFLECT_PROPERTY(m_Index, Engine::EPropertyType::UInt32, "uint32", CATEGORY("PROP_INFORMATION"), READONLY)
    REFLECT_PROPERTY(m_LayerIndex, Engine::EPropertyType::UInt32, "uint32", CATEGORY("PROP_INFORMATION"), READONLY)
    REFLECT_SET(m_TagSet, unordered_set<wstring>, wstring, "wstring", "PROP_TAGS")
    REFLECT_PROPERTY(m_Name, Engine::EPropertyType::String, "wstring", "PROP_NAME")
    REFLECT_BITFLAG(m_Flags, Engine::EPropertyType::BitFlag, "EObjectFlag", "PROP_BITFLAG")
END_REFLECT()

}
