// Auto-generated by ReflectionGenerator.py
#include "Core/Public/Engine_Includes.h"
#include "Core/Public/Reflection/ReflectionMacro.h"
#include "Core/Public/Reflection/ContainerReflection.h"

// [헤더 파일 자동 포함]
#include "Components/Public/Components.h" 
#include "Scene/Public/GameObject.h"

namespace Engine {

// Class: GameObject
BEGIN_REFLECT(GameObject)
    REFLECT_PROPERTY(m_Parent, Engine::EPropertyType::Object, "GameObject")
    REFLECT_VECTOR(m_Childs, vector<GameObject*>, GameObject*, "GameObject*")
    REFLECT_VECTOR(m_Components, vector<Component*>, Component*, "Component*")
    REFLECT_SET(m_TagSet, unordered_set<wstring>, wstring, "wstring")
    REFLECT_PROPERTY(m_Name, Engine::EPropertyType::String, "wstring")
    REFLECT_PROPERTY(m_ID, Engine::EPropertyType::UInt64, "uint64")
    REFLECT_PROPERTY(m_Flags, Engine::EPropertyType::Enum, "EObjectFlag")
END_REFLECT()

}
