// Auto-generated by ReflectionTool
#include "Core/Public/Engine_Includes.h"
#include "Core/Reflection/Public/ReflectionMacro.h"
#include "Core/Reflection/Public/ReflectionContainers.h"

// [Header Includes]
#include "Core/Public/Interface/Component.h"
#include "Core/Public/Structs.h"
#include "Core/Public/Transform.h"
#include "Physics/Components/Collider/Public/Box2DCollider.h"
#include "Physics/Components/Collider/Public/BoxCollider.h"
#include "Physics/Components/Collider/Public/Collider.h"
#include "Render/Camera/Public/Camera.h"
#include "Render/Components/Public/MeshRenderer.h"
#include "Render/Components/Public/RenderComponent.h"
#include "Render/Components/Public/SpriteRenderer.h"
#include "Render/RHI/Public/RHIDefinitions.h"
#include "Render/RHI/Public/RHIShader.h"
#include "Render/Sampler/Public/SamplerDesc.h"
#include "Resource/Components/MeshFilter/Public/MeshFilter.h"
#include "Resource/Material/Public/Material.h"
#include "Resource/Material/Public/MaterialInstance.h"
#include "Resource/Material/Public/MaterialInterface.h"
#include "Resource/Mesh/Public/Mesh.h"
#include "Resource/Model/Public/Model.h"
#include "Resource/Model/Public/Skeleton.h"
#include "Resource/Public/Resource.h"
#include "Resource/Script/Public/Script.h"
#include "Resource/Shader/Public/Shader.h"
#include "Resource/Sprite/Public/Sprite.h"
#include "Resource/Texture/Public/Texture.h"
#include "UI/Button/Public/Button.h"
#include "UI/Public/UIComponent.h"
#include "World/Layer/Public/Layer.h"
#include "World/Public/GameObject.h"
#include "World/Scene/Public/Scene.h"

#pragma push_macro("new")
#undef new

// ==========================================================
// [ENUM REFLECTIONS]
// ==========================================================
#pragma region EnumReflections
// Enum: Engine::ETransformFlag
BEGIN_ENUM(ETransformFlag)
	REFLECT_ENUM_ENTRY(ETransformFlag, None)
	REFLECT_ENUM_ENTRY(ETransformFlag, InheritPosition)
	REFLECT_ENUM_ENTRY(ETransformFlag, InheritRotation)
	REFLECT_ENUM_ENTRY(ETransformFlag, InheritScale)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionX)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionY)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionZ)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockPosition)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationX)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationY)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationZ)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockRotation)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleX)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleY)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleZ)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockScale)
	REFLECT_ENUM_ENTRY(ETransformFlag, Static)
	REFLECT_ENUM_ENTRY(ETransformFlag, AllInherit)
	REFLECT_ENUM_ENTRY(ETransformFlag, AllLocked)
	REFLECT_ENUM_ENTRY(ETransformFlag, Default)
END_ENUM_REFLECT_EX(ETransformFlag, "Engine::ETransformFlag")

// Enum: Engine::ERotationMode
BEGIN_ENUM(ERotationMode)
	REFLECT_ENUM_ENTRY(ERotationMode, Euler)
	REFLECT_ENUM_ENTRY(ERotationMode, QuaternionXYZW)
END_ENUM_REFLECT_EX(ERotationMode, "Engine::ERotationMode")

// Enum: EColliderType
BEGIN_ENUM(EColliderType)
	REFLECT_ENUM_ENTRY(EColliderType, Box)
	REFLECT_ENUM_ENTRY(EColliderType, Box2D)
	REFLECT_ENUM_ENTRY(EColliderType, Sphere)
	REFLECT_ENUM_ENTRY(EColliderType, Capsule)
	REFLECT_ENUM_ENTRY(EColliderType, Mesh)
END_ENUM_REFLECT_EX(EColliderType, "EColliderType")

// Enum: EDrawMode
BEGIN_ENUM(EDrawMode)
	REFLECT_ENUM_ENTRY(EDrawMode, Simple)
	REFLECT_ENUM_ENTRY(EDrawMode, Sliced)
	REFLECT_ENUM_ENTRY(EDrawMode, Tiled)
	REFLECT_ENUM_ENTRY(EDrawMode, Filled)
END_ENUM_REFLECT_EX(EDrawMode, "EDrawMode")

// Enum: Engine::EPipelineType
BEGIN_ENUM(EPipelineType)
	REFLECT_ENUM_ENTRY(EPipelineType, Graphics)
	REFLECT_ENUM_ENTRY(EPipelineType, Compute)
END_ENUM_REFLECT_EX(EPipelineType, "Engine::EPipelineType")

// Enum: Engine::EBlendMode
BEGIN_ENUM(EBlendMode)
	REFLECT_ENUM_ENTRY(EBlendMode, Opaque)
	REFLECT_ENUM_ENTRY(EBlendMode, AlphaBlend)
	REFLECT_ENUM_ENTRY(EBlendMode, Additive)
	REFLECT_ENUM_ENTRY(EBlendMode, NonPremultiplied)
	REFLECT_ENUM_ENTRY(EBlendMode, Masked)
END_ENUM_REFLECT_EX(EBlendMode, "Engine::EBlendMode")

// Enum: Engine::EFillMode
BEGIN_ENUM(EFillMode)
	REFLECT_ENUM_ENTRY(EFillMode, Wireframe)
	REFLECT_ENUM_ENTRY(EFillMode, Solid)
END_ENUM_REFLECT_EX(EFillMode, "Engine::EFillMode")

// Enum: Engine::ECullMode
BEGIN_ENUM(ECullMode)
	REFLECT_ENUM_ENTRY(ECullMode, None)
	REFLECT_ENUM_ENTRY(ECullMode, Front)
	REFLECT_ENUM_ENTRY(ECullMode, Back)
END_ENUM_REFLECT_EX(ECullMode, "Engine::ECullMode")

// Enum: Engine::EFrontFace
BEGIN_ENUM(EFrontFace)
	REFLECT_ENUM_ENTRY(EFrontFace, Clockwise)
	REFLECT_ENUM_ENTRY(EFrontFace, CounterClockwise)
END_ENUM_REFLECT_EX(EFrontFace, "Engine::EFrontFace")

// Enum: Engine::EDepthMode
BEGIN_ENUM(EDepthMode)
	REFLECT_ENUM_ENTRY(EDepthMode, None)
	REFLECT_ENUM_ENTRY(EDepthMode, ReadOnly)
	REFLECT_ENUM_ENTRY(EDepthMode, ReadWrite)
END_ENUM_REFLECT_EX(EDepthMode, "Engine::EDepthMode")

// Enum: Engine::ETopology
BEGIN_ENUM(ETopology)
	REFLECT_ENUM_ENTRY(ETopology, TriangleList)
	REFLECT_ENUM_ENTRY(ETopology, TriangleStrip)
	REFLECT_ENUM_ENTRY(ETopology, LineList)
	REFLECT_ENUM_ENTRY(ETopology, LineStrip)
	REFLECT_ENUM_ENTRY(ETopology, PointList)
END_ENUM_REFLECT_EX(ETopology, "Engine::ETopology")

// Enum: Engine::ECompareOp
BEGIN_ENUM(ECompareOp)
	REFLECT_ENUM_ENTRY(ECompareOp, Never)
	REFLECT_ENUM_ENTRY(ECompareOp, Less)
	REFLECT_ENUM_ENTRY(ECompareOp, Equal)
	REFLECT_ENUM_ENTRY(ECompareOp, LessOrEqual)
	REFLECT_ENUM_ENTRY(ECompareOp, Greater)
	REFLECT_ENUM_ENTRY(ECompareOp, NotEqual)
	REFLECT_ENUM_ENTRY(ECompareOp, GreaterOrEqual)
	REFLECT_ENUM_ENTRY(ECompareOp, Always)
END_ENUM_REFLECT_EX(ECompareOp, "Engine::ECompareOp")

// Enum: Engine::ESamplerFilter
BEGIN_ENUM(ESamplerFilter)
	REFLECT_ENUM_ENTRY(ESamplerFilter, Point)
	REFLECT_ENUM_ENTRY(ESamplerFilter, Linear)
	REFLECT_ENUM_ENTRY(ESamplerFilter, Anisotropic)
END_ENUM_REFLECT_EX(ESamplerFilter, "Engine::ESamplerFilter")

// Enum: Engine::ESamplerAddressMode
BEGIN_ENUM(ESamplerAddressMode)
	REFLECT_ENUM_ENTRY(ESamplerAddressMode, Wrap)
	REFLECT_ENUM_ENTRY(ESamplerAddressMode, Mirror)
	REFLECT_ENUM_ENTRY(ESamplerAddressMode, Clamp)
	REFLECT_ENUM_ENTRY(ESamplerAddressMode, Border)
	REFLECT_ENUM_ENTRY(ESamplerAddressMode, MirrorOnce)
END_ENUM_REFLECT_EX(ESamplerAddressMode, "Engine::ESamplerAddressMode")

// Enum: EPipelineOverrideFlag
BEGIN_ENUM(EPipelineOverrideFlag)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, None)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, BlendMode)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, CullMode)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, FillMode)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, DepthMode)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, DepthCompareOp)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, Count)
END_ENUM_REFLECT_EX(EPipelineOverrideFlag, "EPipelineOverrideFlag")

// Enum: Engine::EMaterialParameterType
BEGIN_ENUM(EMaterialParameterType)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Float)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Float2)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Float3)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Float4)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Int)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Bool)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Matrix)
END_ENUM_REFLECT_EX(EMaterialParameterType, "Engine::EMaterialParameterType")

// Enum: Engine::EResourceType
BEGIN_ENUM(EResourceType)
	REFLECT_ENUM_ENTRY(EResourceType, Unknown)
	REFLECT_ENUM_ENTRY(EResourceType, Texture)
	REFLECT_ENUM_ENTRY(EResourceType, Sprite)
	REFLECT_ENUM_ENTRY(EResourceType, Material)
	REFLECT_ENUM_ENTRY(EResourceType, MaterialInstance)
	REFLECT_ENUM_ENTRY(EResourceType, Shader)
	REFLECT_ENUM_ENTRY(EResourceType, Mesh)
	REFLECT_ENUM_ENTRY(EResourceType, Model)
	REFLECT_ENUM_ENTRY(EResourceType, Animation)
	REFLECT_ENUM_ENTRY(EResourceType, AudioClip)
	REFLECT_ENUM_ENTRY(EResourceType, Skeleton)
	REFLECT_ENUM_ENTRY(EResourceType, Prefab)
	REFLECT_ENUM_ENTRY(EResourceType, Script)
	REFLECT_ENUM_ENTRY(EResourceType, Scene)
	REFLECT_ENUM_ENTRY(EResourceType, Save)
END_ENUM_REFLECT_EX(EResourceType, "Engine::EResourceType")

// Enum: Engine::ELayerFlags
BEGIN_ENUM(ELayerFlags)
	REFLECT_ENUM_ENTRY(ELayerFlags, None)
	REFLECT_ENUM_ENTRY(ELayerFlags, Active)
	REFLECT_ENUM_ENTRY(ELayerFlags, Visible)
	REFLECT_ENUM_ENTRY(ELayerFlags, Default)
END_ENUM_REFLECT_EX(ELayerFlags, "Engine::ELayerFlags")

// Enum: EObjectFlag
BEGIN_ENUM(EObjectFlag)
	REFLECT_ENUM_ENTRY(EObjectFlag, None)
	REFLECT_ENUM_ENTRY(EObjectFlag, Active)
	REFLECT_ENUM_ENTRY(EObjectFlag, Visible)
	REFLECT_ENUM_ENTRY(EObjectFlag, Paused)
	REFLECT_ENUM_ENTRY(EObjectFlag, Dead)
	REFLECT_ENUM_ENTRY(EObjectFlag, Default)
END_ENUM_REFLECT_EX(EObjectFlag, "EObjectFlag")

#pragma endregion

// ==========================================================
// [CLASS/STRUCT REFLECTIONS]
// ==========================================================
#pragma region ClassStructReflections
#pragma region STRUCT: Engine::tagComponentDesc
BEGIN_PROPERTIES(tagComponentDesc)
	REFLECT_PROPERTY(tagComponentDesc, Active, "bool", Engine::EPropertyType::Bool, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagComponentDesc, Tag, "wstring", Engine::EPropertyType::Wstring, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagComponentDesc, Owner, "class GameObject", Engine::EPropertyType::Object, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(tagComponentDesc)
IMPLEMENT_CLASS_EX(tagComponentDesc, "Engine::tagComponentDesc", "")

#pragma endregion // STRUCT: Engine::tagComponentDesc

#pragma region CLASS: Engine::Component
BEGIN_PROPERTIES(Component)
	REFLECT_PROPERTY(Component, m_Active, "bool", Engine::EPropertyType::Bool, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Component, m_Dirty, "bool", Engine::EPropertyType::Bool, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Component, m_Tag, "wstring", Engine::EPropertyType::Wstring, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(Component)
IMPLEMENT_CLASS_EX(Component, "Engine::Component", "Engine::Base")

#pragma endregion // CLASS: Engine::Component

#pragma region STRUCT: Engine::AABB
BEGIN_PROPERTIES(AABB)
	REFLECT_PROPERTY(AABB, Min, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(AABB, Max, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(AABB)
IMPLEMENT_CLASS_EX(AABB, "Engine::AABB", "")

#pragma endregion // STRUCT: Engine::AABB

#pragma region STRUCT: Engine::Rect
BEGIN_PROPERTIES(Rect)
	REFLECT_PROPERTY(Rect, Left, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Rect, Top, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Rect, Width, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Rect, Height, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(Rect)
IMPLEMENT_CLASS_EX(Rect, "Engine::Rect", "")

#pragma endregion // STRUCT: Engine::Rect

#pragma region STRUCT: Engine::Vertex
BEGIN_PROPERTIES(Vertex)
	REFLECT_PROPERTY(Vertex, position, "glm::vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Vertex, normal, "glm::vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Vertex, texCoord, "glm::vec2", Engine::EPropertyType::Vector2, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Vertex, tangent, "glm::vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Vertex, bitangent, "glm::vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Vertex, color, "glm::vec4", Engine::EPropertyType::Vector4, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(Vertex)
IMPLEMENT_CLASS_EX(Vertex, "Engine::Vertex", "")

#pragma endregion // STRUCT: Engine::Vertex

#pragma region STRUCT: Engine::tagTransformDesc
BEGIN_PROPERTIES(tagTransformDesc)
	REFLECT_PROPERTY(tagTransformDesc, Position, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTransformDesc, Rotation, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTransformDesc, Scale, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(tagTransformDesc)
IMPLEMENT_CLASS_EX(tagTransformDesc, "Engine::tagTransformDesc", "")

#pragma endregion // STRUCT: Engine::tagTransformDesc

#pragma region CLASS: Engine::Transform
BEGIN_METADATA(Transform, m_Position)
	EDITABLE
END_METADATA

BEGIN_METADATA(Transform, m_RotationMode)
	EDITABLE
END_METADATA

BEGIN_METADATA(Transform, m_Rotation)
	EDITABLE
	EDITCONDITION("!m_RotationMode", ERotationMode::Euler, true)
	ONCHANGED("SetRotation", "m_Rotation")
END_METADATA

BEGIN_METADATA(Transform, m_EulerRotation)
	EDITABLE
	EDITCONDITION("m_RotationMode", ERotationMode::Euler, true)
	ONCHANGED("SetRotation", "m_EulerRotation")
END_METADATA

BEGIN_METADATA(Transform, m_Scale)
	EDITABLE
END_METADATA

BEGIN_METADATA(Transform, m_LocalMatrix)
	NAME("PROP_LOCALMATRIX")
	READONLY
END_METADATA

BEGIN_METADATA(Transform, m_WorldMatrix)
	NAME("PROP_WORLDMATRIX")
	READONLY
END_METADATA

BEGIN_METADATA(Transform, m_Flags)
	EDITABLE
	NAME("PROP_BITFLAG")
END_METADATA
BEGIN_PROPERTIES(Transform)
	REFLECT_PROPERTY(Transform, m_Position, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{Transform_m_Position_Meta})
	REFLECT_PROPERTY(Transform, m_RotationMode, "Engine::ERotationMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{Transform_m_RotationMode_Meta})
	REFLECT_PROPERTY(Transform, m_Rotation, "quat", Engine::EPropertyType::Quaternion, std::span<const Engine::MetadataEntry>{Transform_m_Rotation_Meta})
	REFLECT_PROPERTY(Transform, m_EulerRotation, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{Transform_m_EulerRotation_Meta})
	REFLECT_PROPERTY(Transform, m_Scale, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{Transform_m_Scale_Meta})
	REFLECT_PROPERTY(Transform, m_LocalMatrix, "mat4", Engine::EPropertyType::Matrix4, std::span<const Engine::MetadataEntry>{Transform_m_LocalMatrix_Meta})
	REFLECT_PROPERTY(Transform, m_WorldMatrix, "mat4", Engine::EPropertyType::Matrix4, std::span<const Engine::MetadataEntry>{Transform_m_WorldMatrix_Meta})
	REFLECT_PROPERTY(Transform, m_Flags, "Engine::ETransformFlag", Engine::EPropertyType::BitFlag, std::span<const Engine::MetadataEntry>{Transform_m_Flags_Meta})
END_PROPERTIES
DECLARE_FUNCTION_PARAMS(Transform, SetRotation_quat)
	FUNCTION_PARAM("quat", Engine::EPropertyType::Quaternion)
END_FUNCTION_PARAMS
DECLARE_FUNCTION_PARAMS(Transform, SetRotation_vec3)
	FUNCTION_PARAM("vec3", Engine::EPropertyType::Vector3)
END_FUNCTION_PARAMS
BEGIN_FUNCTIONS(Transform)
	REFLECT_FUNCTION_OVERLOAD_EX(Transform, "Engine::Transform", "SetRotation", "SetRotation(const quat&)", static_cast<void (Transform::*)(const quat&)>(&Transform::SetRotation), "void", Engine::EPropertyType::None, Transform_SetRotation_quat_Params)
	REFLECT_FUNCTION_OVERLOAD_EX(Transform, "Engine::Transform", "SetRotation", "SetRotation(const vec3&)", static_cast<void (Transform::*)(const vec3&)>(&Transform::SetRotation), "void", Engine::EPropertyType::None, Transform_SetRotation_vec3_Params)
END_FUNCTIONS
IMPLEMENT_CLASS_EX(Transform, "Engine::Transform", "Engine::Component")

#pragma endregion // CLASS: Engine::Transform

#pragma region CLASS: Engine::Box2DCollider
BEGIN_METADATA(Box2DCollider, m_Center)
	EDITABLE
END_METADATA

BEGIN_METADATA(Box2DCollider, m_Extent)
	EDITABLE
END_METADATA
BEGIN_PROPERTIES(Box2DCollider)
	REFLECT_PROPERTY(Box2DCollider, m_Center, "vec2", Engine::EPropertyType::Vector2, std::span<const Engine::MetadataEntry>{Box2DCollider_m_Center_Meta})
	REFLECT_PROPERTY(Box2DCollider, m_Extent, "vec2", Engine::EPropertyType::Vector2, std::span<const Engine::MetadataEntry>{Box2DCollider_m_Extent_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(Box2DCollider)
IMPLEMENT_CLASS_EX(Box2DCollider, "Engine::Box2DCollider", "Engine::Collider")

#pragma endregion // CLASS: Engine::Box2DCollider

#pragma region CLASS: Engine::BoxCollider
BEGIN_METADATA(BoxCollider, m_Center)
	EDITABLE
END_METADATA

BEGIN_METADATA(BoxCollider, m_Extents)
	EDITABLE
END_METADATA
BEGIN_PROPERTIES(BoxCollider)
	REFLECT_PROPERTY(BoxCollider, m_Center, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{BoxCollider_m_Center_Meta})
	REFLECT_PROPERTY(BoxCollider, m_Extents, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{BoxCollider_m_Extents_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(BoxCollider)
IMPLEMENT_CLASS_EX(BoxCollider, "Engine::BoxCollider", "Engine::Collider")

#pragma endregion // CLASS: Engine::BoxCollider

#pragma region CLASS: Engine::Collider
BEGIN_METADATA(Collider, m_Type)
	EDITABLE
END_METADATA

BEGIN_METADATA(Collider, m_DrawCollider)
	EDITABLE
END_METADATA
BEGIN_PROPERTIES(Collider)
	REFLECT_PROPERTY(Collider, m_Type, "EColliderType", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{Collider_m_Type_Meta})
	REFLECT_PROPERTY(Collider, m_DrawCollider, "bool", Engine::EPropertyType::Bool, std::span<const Engine::MetadataEntry>{Collider_m_DrawCollider_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(Collider)
IMPLEMENT_CLASS_EX(Collider, "Engine::Collider", "Engine::Component")

#pragma endregion // CLASS: Engine::Collider

#pragma region CLASS: Engine::Camera
BEGIN_METADATA(Camera, m_FOV)
	EDITABLE
	EDITCONDITION("m_IsPerspective")
END_METADATA

BEGIN_METADATA(Camera, m_Near)
	EDITABLE
END_METADATA

BEGIN_METADATA(Camera, m_Far)
	EDITABLE
END_METADATA

BEGIN_METADATA(Camera, m_Aspect)
	EDITABLE
	EDITCONDITION("m_IsPerspective")
END_METADATA

BEGIN_METADATA(Camera, m_OrthoSize)
	EDITABLE
	EDITCONDITION("!m_IsPerspective")
END_METADATA

BEGIN_METADATA(Camera, m_IsPerspective)
	EDITABLE
END_METADATA

BEGIN_METADATA(Camera, m_ProjMatrix)
	READONLY
END_METADATA

BEGIN_METADATA(Camera, m_ViewMatrix)
	READONLY
END_METADATA
BEGIN_PROPERTIES(Camera)
	REFLECT_PROPERTY(Camera, m_FOV, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{Camera_m_FOV_Meta})
	REFLECT_PROPERTY(Camera, m_Near, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{Camera_m_Near_Meta})
	REFLECT_PROPERTY(Camera, m_Far, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{Camera_m_Far_Meta})
	REFLECT_PROPERTY(Camera, m_Aspect, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{Camera_m_Aspect_Meta})
	REFLECT_PROPERTY(Camera, m_OrthoSize, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{Camera_m_OrthoSize_Meta})
	REFLECT_PROPERTY(Camera, m_IsPerspective, "bool", Engine::EPropertyType::Bool, std::span<const Engine::MetadataEntry>{Camera_m_IsPerspective_Meta})
	REFLECT_PROPERTY(Camera, m_ProjMatrix, "glm::mat4", Engine::EPropertyType::Matrix4, std::span<const Engine::MetadataEntry>{Camera_m_ProjMatrix_Meta})
	REFLECT_PROPERTY(Camera, m_ViewMatrix, "glm::mat4", Engine::EPropertyType::Matrix4, std::span<const Engine::MetadataEntry>{Camera_m_ViewMatrix_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(Camera)
IMPLEMENT_CLASS_EX(Camera, "Engine::Camera", "Engine::Component")

#pragma endregion // CLASS: Engine::Camera

#pragma region CLASS: Engine::MeshRenderer
EMPTY_PROPERTIES(MeshRenderer)
EMPTY_FUNCTIONS(MeshRenderer)
IMPLEMENT_CLASS_EX(MeshRenderer, "Engine::MeshRenderer", "Engine::RenderComponent")

#pragma endregion // CLASS: Engine::MeshRenderer

#pragma region CLASS: Engine::RenderComponent
BEGIN_METADATA(RenderComponent, m_RenderPassID)
	EDITABLE
	CATEGORY("PROP_INFORMATION")
END_METADATA

BEGIN_METADATA(RenderComponent, m_MaterialInstances)
	EDITABLE
END_METADATA

DECLARE_CONTAINER_INFO(RenderComponent, m_MaterialInstances_Root, "ResourceHandle<MaterialInstance>", Engine::EPropertyType::ResourceHandle, Engine::LinearContainerAccessor<vector<ResourceHandle<MaterialInstance>>, ResourceHandle<MaterialInstance>>::Get())
BEGIN_PROPERTIES(RenderComponent)
	REFLECT_PROPERTY(RenderComponent, m_RenderPassID, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{RenderComponent_m_RenderPassID_Meta})
	REFLECT_CONTAINER_PROPERTY(RenderComponent, m_MaterialInstances, "vector<ResourceHandle<MaterialInstance>>", Engine::EPropertyType::Array, &RenderComponent_m_MaterialInstances_Root_ContainerData, std::span<const Engine::MetadataEntry>{RenderComponent_m_MaterialInstances_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(RenderComponent)
IMPLEMENT_CLASS_EX(RenderComponent, "Engine::RenderComponent", "Engine::Component")

#pragma endregion // CLASS: Engine::RenderComponent

#pragma region CLASS: Engine::SpriteRenderer
BEGIN_METADATA(SpriteRenderer, m_Tiling)
	EDITABLE
	DEFAULT(vec2(1.f, 1.f))
END_METADATA

BEGIN_METADATA(SpriteRenderer, m_Mesh)
	EDITABLE
END_METADATA

BEGIN_METADATA(SpriteRenderer, m_Sprite)
	EDITABLE
END_METADATA

BEGIN_METADATA(SpriteRenderer, m_CachedSpriteVersion)
	CATEGORY("DETAIL")
	READONLY
	NOSERIALIZE
END_METADATA

BEGIN_METADATA(SpriteRenderer, m_DrawMode)
	EDITABLE
END_METADATA
BEGIN_PROPERTIES(SpriteRenderer)
	REFLECT_PROPERTY(SpriteRenderer, m_Tiling, "vec2", Engine::EPropertyType::Vector2, std::span<const Engine::MetadataEntry>{SpriteRenderer_m_Tiling_Meta})
	REFLECT_PROPERTY(SpriteRenderer, m_Mesh, "ResourceHandle<Mesh>", Engine::EPropertyType::ResourceHandle, std::span<const Engine::MetadataEntry>{SpriteRenderer_m_Mesh_Meta})
	REFLECT_PROPERTY(SpriteRenderer, m_Sprite, "ResourceHandle<Sprite>", Engine::EPropertyType::ResourceHandle, std::span<const Engine::MetadataEntry>{SpriteRenderer_m_Sprite_Meta})
	REFLECT_PROPERTY(SpriteRenderer, m_CachedSpriteVersion, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{SpriteRenderer_m_CachedSpriteVersion_Meta})
	REFLECT_PROPERTY(SpriteRenderer, m_DrawMode, "EDrawMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{SpriteRenderer_m_DrawMode_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(SpriteRenderer)
IMPLEMENT_CLASS_EX(SpriteRenderer, "Engine::SpriteRenderer", "Engine::RenderComponent")

#pragma endregion // CLASS: Engine::SpriteRenderer

#pragma region CLASS: Engine::RHIShader
BEGIN_PROPERTIES(RHIShader)
	REFLECT_PROPERTY(RHIShader, m_ShaderType, "EShaderType", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(RHIShader, m_EntryPoint, "string", Engine::EPropertyType::String, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(RHIShader)
IMPLEMENT_CLASS_EX(RHIShader, "Engine::RHIShader", "Engine::RHIResource")

#pragma endregion // CLASS: Engine::RHIShader

#pragma region STRUCT: Engine::tagSamplerDesc
BEGIN_PROPERTIES(tagSamplerDesc)
	REFLECT_PROPERTY(tagSamplerDesc, MinFilter, "Engine::ESamplerFilter", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagSamplerDesc, MagFilter, "Engine::ESamplerFilter", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagSamplerDesc, MipFilter, "Engine::ESamplerFilter", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagSamplerDesc, AddressU, "Engine::ESamplerAddressMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagSamplerDesc, AddressV, "Engine::ESamplerAddressMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagSamplerDesc, AddressW, "Engine::ESamplerAddressMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagSamplerDesc, MaxAnisotropy, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagSamplerDesc, BorderColor, "vec4", Engine::EPropertyType::Vector4, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(tagSamplerDesc)
IMPLEMENT_CLASS_EX(tagSamplerDesc, "Engine::tagSamplerDesc", "")

#pragma endregion // STRUCT: Engine::tagSamplerDesc

#pragma region CLASS: Engine::MeshFilter
BEGIN_PROPERTIES(MeshFilter)
	REFLECT_PROPERTY(MeshFilter, m_MeshHandle, "ResourceHandle<Mesh>", Engine::EPropertyType::ResourceHandle, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(MeshFilter)
IMPLEMENT_CLASS_EX(MeshFilter, "Engine::MeshFilter", "Engine::Component")

#pragma endregion // CLASS: Engine::MeshFilter

#pragma region CLASS: Engine::Material
EMPTY_PROPERTIES(Material)
EMPTY_FUNCTIONS(Material)
IMPLEMENT_CLASS_EX(Material, "Engine::Material", "Engine::MaterialInterface")

#pragma endregion // CLASS: Engine::Material

#pragma region CLASS: Engine::MaterialInstance
BEGIN_PROPERTIES(MaterialInstance)
	REFLECT_PROPERTY(MaterialInstance, m_BaseMaterialHandle, "ResourceHandle<Material>", Engine::EPropertyType::ResourceHandle, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(MaterialInstance, m_OverrideFlags, "EPipelineOverrideFlag", Engine::EPropertyType::BitFlag, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(MaterialInstance)
IMPLEMENT_CLASS_EX(MaterialInstance, "Engine::MaterialInstance", "Engine::MaterialInterface")

#pragma endregion // CLASS: Engine::MaterialInstance

#pragma region STRUCT: Engine::MaterialTextureBinding
BEGIN_PROPERTIES(MaterialTextureBinding)
	REFLECT_PROPERTY(MaterialTextureBinding, name, "string", Engine::EPropertyType::String, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(MaterialTextureBinding, texture, "ResourceHandle<Texture>", Engine::EPropertyType::ResourceHandle, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(MaterialTextureBinding, hasCustomSampler, "bool", Engine::EPropertyType::Bool, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(MaterialTextureBinding, samplerDesc, "Engine::tagSamplerDesc", Engine::EPropertyType::Struct, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(MaterialTextureBinding)
IMPLEMENT_CLASS_EX(MaterialTextureBinding, "Engine::MaterialTextureBinding", "")

#pragma endregion // STRUCT: Engine::MaterialTextureBinding

#pragma region STRUCT: Engine::MaterialParameter
DECLARE_CONTAINER_INFO(MaterialParameter, data_Root, "uint8", Engine::EPropertyType::UInt8, Engine::LinearContainerAccessor<vector<uint8>, uint8>::Get())
BEGIN_PROPERTIES(MaterialParameter)
	REFLECT_PROPERTY(MaterialParameter, type, "Engine::EMaterialParameterType", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_CONTAINER_PROPERTY(MaterialParameter, data, "vector<uint8>", Engine::EPropertyType::Array, &MaterialParameter_data_Root_ContainerData, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(MaterialParameter)
IMPLEMENT_CLASS_EX(MaterialParameter, "Engine::MaterialParameter", "")

#pragma endregion // STRUCT: Engine::MaterialParameter

#pragma region CLASS: Engine::MaterialInterface
BEGIN_METADATA(MaterialInterface, m_BlendMode)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_CullMode)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_FillMode)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_DepthMode)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_DepthCompareOp)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_Parameters)
	CATEGORY(L"Parameter")
END_METADATA

DECLARE_MAP_INFO(MaterialInterface, m_Parameters_Root, "string", Engine::EPropertyType::String, "Engine::MaterialParameter", Engine::EPropertyType::Struct, Engine::MapAccessor<unordered_map<string, MaterialParameter>>::Get())
BEGIN_METADATA(MaterialInterface, m_TextureBindings)
	CATEGORY("Texture")
END_METADATA

DECLARE_CONTAINER_INFO(MaterialInterface, m_TextureBindings_Root, "Engine::MaterialTextureBinding", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<MaterialTextureBinding>, MaterialTextureBinding>::Get())
BEGIN_PROPERTIES(MaterialInterface)
	REFLECT_PROPERTY(MaterialInterface, m_BlendMode, "Engine::EBlendMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{MaterialInterface_m_BlendMode_Meta})
	REFLECT_PROPERTY(MaterialInterface, m_CullMode, "Engine::ECullMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{MaterialInterface_m_CullMode_Meta})
	REFLECT_PROPERTY(MaterialInterface, m_FillMode, "Engine::EFillMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{MaterialInterface_m_FillMode_Meta})
	REFLECT_PROPERTY(MaterialInterface, m_DepthMode, "Engine::EDepthMode", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{MaterialInterface_m_DepthMode_Meta})
	REFLECT_PROPERTY(MaterialInterface, m_DepthCompareOp, "Engine::ECompareOp", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{MaterialInterface_m_DepthCompareOp_Meta})
	REFLECT_PROPERTY(MaterialInterface, m_VertexShaderHandle, "ResourceHandle<Shader>", Engine::EPropertyType::ResourceHandle, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(MaterialInterface, m_PixelShaderHandle, "ResourceHandle<Shader>", Engine::EPropertyType::ResourceHandle, std::span<const Engine::MetadataEntry>{})
	REFLECT_CONTAINER_PROPERTY(MaterialInterface, m_Parameters, "unordered_map<string, MaterialParameter>", Engine::EPropertyType::Map, &MaterialInterface_m_Parameters_Root_ContainerData, std::span<const Engine::MetadataEntry>{MaterialInterface_m_Parameters_Meta})
	REFLECT_CONTAINER_PROPERTY(MaterialInterface, m_TextureBindings, "vector<MaterialTextureBinding>", Engine::EPropertyType::Array, &MaterialInterface_m_TextureBindings_Root_ContainerData, std::span<const Engine::MetadataEntry>{MaterialInterface_m_TextureBindings_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(MaterialInterface)
IMPLEMENT_CLASS_EX(MaterialInterface, "Engine::MaterialInterface", "Engine::Resource")

#pragma endregion // CLASS: Engine::MaterialInterface

#pragma region CLASS: Engine::Mesh
BEGIN_METADATA(Mesh, m_Topology)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(Mesh, m_VertexCount)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(Mesh, m_IndexCount)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(Mesh, m_BoundingBoxMin)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(Mesh, m_BoundingBoxMax)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA
BEGIN_PROPERTIES(Mesh)
	REFLECT_PROPERTY(Mesh, m_Topology, "Engine::ETopology", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{Mesh_m_Topology_Meta})
	REFLECT_PROPERTY(Mesh, m_VertexCount, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{Mesh_m_VertexCount_Meta})
	REFLECT_PROPERTY(Mesh, m_IndexCount, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{Mesh_m_IndexCount_Meta})
	REFLECT_PROPERTY(Mesh, m_BoundingBoxMin, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{Mesh_m_BoundingBoxMin_Meta})
	REFLECT_PROPERTY(Mesh, m_BoundingBoxMax, "vec3", Engine::EPropertyType::Vector3, std::span<const Engine::MetadataEntry>{Mesh_m_BoundingBoxMax_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(Mesh)
IMPLEMENT_CLASS_EX(Mesh, "Engine::Mesh", "Engine::Resource")

#pragma endregion // CLASS: Engine::Mesh

#pragma region CLASS: Engine::Model
DECLARE_CONTAINER_INFO(Model, m_Materials_Root, "Engine::Material", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<Material*>, Material*>::Get())
DECLARE_CONTAINER_INFO(Model, m_Meshes_Root, "Engine::Mesh", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<Mesh*>, Mesh*>::Get())
BEGIN_PROPERTIES(Model)
	REFLECT_CONTAINER_PROPERTY(Model, m_Materials, "vector<Material*>", Engine::EPropertyType::Array, &Model_m_Materials_Root_ContainerData, std::span<const Engine::MetadataEntry>{})
	REFLECT_CONTAINER_PROPERTY(Model, m_Meshes, "vector<Mesh*>", Engine::EPropertyType::Array, &Model_m_Meshes_Root_ContainerData, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Model, m_Skeleton, "Engine::Skeleton", Engine::EPropertyType::Object, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(Model)
IMPLEMENT_CLASS_EX(Model, "Engine::Model", "Engine::Resource")

#pragma endregion // CLASS: Engine::Model

#pragma region CLASS: Engine::Skeleton
BEGIN_METADATA(Skeleton, m_Bones)
	CATEGORY("PROP_BONE")
END_METADATA

DECLARE_CONTAINER_INFO(Skeleton, m_Bones_Root, "Bone", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<Bone>, Bone>::Get())
BEGIN_METADATA(Skeleton, m_BoneMap)
	CATEGORY("PROP_BONE")
END_METADATA

DECLARE_MAP_INFO(Skeleton, m_BoneMap_Root, "wstring", Engine::EPropertyType::Wstring, "uint32", Engine::EPropertyType::UInt32, Engine::MapAccessor<unordered_map<wstring, uint32>>::Get())
BEGIN_PROPERTIES(Skeleton)
	REFLECT_CONTAINER_PROPERTY(Skeleton, m_Bones, "vector<Bone>", Engine::EPropertyType::Array, &Skeleton_m_Bones_Root_ContainerData, std::span<const Engine::MetadataEntry>{Skeleton_m_Bones_Meta})
	REFLECT_CONTAINER_PROPERTY(Skeleton, m_BoneMap, "unordered_map<wstring, uint32>", Engine::EPropertyType::Map, &Skeleton_m_BoneMap_Root_ContainerData, std::span<const Engine::MetadataEntry>{Skeleton_m_BoneMap_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(Skeleton)
IMPLEMENT_CLASS_EX(Skeleton, "Engine::Skeleton", "Engine::Resource")

#pragma endregion // CLASS: Engine::Skeleton

#pragma region STRUCT: Engine::tagResourceBinaryHeader
BEGIN_PROPERTIES(tagResourceBinaryHeader)
	REFLECT_PROPERTY(tagResourceBinaryHeader, MagicNumber, "uint64", Engine::EPropertyType::UInt64, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagResourceBinaryHeader, ResourceType, "Engine::EResourceType", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagResourceBinaryHeader, Version, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(tagResourceBinaryHeader)
IMPLEMENT_CLASS_EX(tagResourceBinaryHeader, "Engine::tagResourceBinaryHeader", "")

#pragma endregion // STRUCT: Engine::tagResourceBinaryHeader

#pragma region CLASS: Engine::Resource
BEGIN_METADATA(Resource, m_Version)
	READONLY
END_METADATA

BEGIN_METADATA(Resource, m_ResourceType)
	READONLY
END_METADATA

BEGIN_METADATA(Resource, m_Key)
	READONLY
END_METADATA

BEGIN_METADATA(Resource, m_Path)
	READONLY
END_METADATA
BEGIN_PROPERTIES(Resource)
	REFLECT_PROPERTY(Resource, m_Version, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{Resource_m_Version_Meta})
	REFLECT_PROPERTY(Resource, m_ResourceType, "Engine::EResourceType", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{Resource_m_ResourceType_Meta})
	REFLECT_PROPERTY(Resource, m_Key, "wstring", Engine::EPropertyType::Wstring, std::span<const Engine::MetadataEntry>{Resource_m_Key_Meta})
	REFLECT_PROPERTY(Resource, m_Path, "wstring", Engine::EPropertyType::Wstring, std::span<const Engine::MetadataEntry>{Resource_m_Path_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(Resource)
IMPLEMENT_CLASS_EX(Resource, "Engine::Resource", "Engine::SerializableInterface")

#pragma endregion // CLASS: Engine::Resource

#pragma region CLASS: Engine::Script
EMPTY_PROPERTIES(Script)
EMPTY_FUNCTIONS(Script)
IMPLEMENT_CLASS_EX(Script, "Engine::Script", "Engine::Resource")

#pragma endregion // CLASS: Engine::Script

#pragma region CLASS: Engine::Shader
BEGIN_METADATA(Shader, m_RHIShader)
	NOSERIALIZE
END_METADATA
BEGIN_PROPERTIES(Shader)
	REFLECT_PROPERTY(Shader, m_ShaderType, "EShaderType", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Shader, m_SpirvPath, "wstring", Engine::EPropertyType::Wstring, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Shader, m_EntryPoint, "string", Engine::EPropertyType::String, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Shader, m_NumSamplers, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Shader, m_NumStorageTextures, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Shader, m_NumStorageBuffers, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Shader, m_NumUniformBuffers, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Shader, m_RHIShader, "Engine::RHIShader", Engine::EPropertyType::Object, std::span<const Engine::MetadataEntry>{Shader_m_RHIShader_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(Shader)
IMPLEMENT_CLASS_EX(Shader, "Engine::Shader", "Engine::Resource")

#pragma endregion // CLASS: Engine::Shader

#pragma region CLASS: Engine::Sprite
BEGIN_METADATA(Sprite, m_Texture)
	READONLY
END_METADATA

BEGIN_METADATA(Sprite, m_Pivot)
	DEFAULT(vec2(0.5f, 0.5f))
END_METADATA
BEGIN_PROPERTIES(Sprite)
	REFLECT_PROPERTY(Sprite, m_Texture, "ResourceHandle<Texture>", Engine::EPropertyType::ResourceHandle, std::span<const Engine::MetadataEntry>{Sprite_m_Texture_Meta})
	REFLECT_PROPERTY(Sprite, m_Region, "Engine::Rect", Engine::EPropertyType::Struct, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Sprite, m_Pivot, "vec2", Engine::EPropertyType::Vector2, std::span<const Engine::MetadataEntry>{Sprite_m_Pivot_Meta})
END_PROPERTIES
EMPTY_FUNCTIONS(Sprite)
IMPLEMENT_CLASS_EX(Sprite, "Engine::Sprite", "Engine::Resource")

#pragma endregion // CLASS: Engine::Sprite

#pragma region STRUCT: Engine::tagTextureBinaryHeader
BEGIN_PROPERTIES(tagTextureBinaryHeader)
	REFLECT_PROPERTY(tagTextureBinaryHeader, Width, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTextureBinaryHeader, Height, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTextureBinaryHeader, Depth, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTextureBinaryHeader, MipLevels, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTextureBinaryHeader, ArraySize, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTextureBinaryHeader, Format, "ETextureFormat", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTextureBinaryHeader, Dimension, "ETextureDimension", Engine::EPropertyType::Enum, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(tagTextureBinaryHeader, DataSize, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(tagTextureBinaryHeader)
IMPLEMENT_CLASS_EX(tagTextureBinaryHeader, "Engine::tagTextureBinaryHeader", "")

#pragma endregion // STRUCT: Engine::tagTextureBinaryHeader

#pragma region CLASS: Engine::Texture
BEGIN_PROPERTIES(Texture)
	REFLECT_PROPERTY(Texture, m_PixelPerUnit, "f32", Engine::EPropertyType::F32, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(Texture)
IMPLEMENT_CLASS_EX(Texture, "Engine::Texture", "Engine::Resource")

#pragma endregion // CLASS: Engine::Texture

#pragma region CLASS: Engine::Button
EMPTY_PROPERTIES(Button)
EMPTY_FUNCTIONS(Button)
IMPLEMENT_CLASS_EX(Button, "Engine::Button", "Engine::UIComponent")

#pragma endregion // CLASS: Engine::Button

#pragma region CLASS: Engine::UIComponent
EMPTY_PROPERTIES(UIComponent)
EMPTY_FUNCTIONS(UIComponent)
IMPLEMENT_CLASS_EX(UIComponent, "Engine::UIComponent", "Engine::Component")

#pragma endregion // CLASS: Engine::UIComponent

#pragma region CLASS: Engine::Layer
DECLARE_CONTAINER_INFO(Layer, m_GameObjects_Root, "class GameObject", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<class GameObject*>, class GameObject*>::Get())
DECLARE_CONTAINER_INFO(Layer, m_DeadGameObjects_Root, "class GameObject", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<class GameObject*>, class GameObject*>::Get())
BEGIN_PROPERTIES(Layer)
	REFLECT_PROPERTY(Layer, m_Index, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Layer, m_Name, "wstring", Engine::EPropertyType::Wstring, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Layer, m_Flags, "Engine::ELayerFlags", Engine::EPropertyType::BitFlag, std::span<const Engine::MetadataEntry>{})
	REFLECT_CONTAINER_PROPERTY(Layer, m_GameObjects, "vector<class GameObject*>", Engine::EPropertyType::Array, &Layer_m_GameObjects_Root_ContainerData, std::span<const Engine::MetadataEntry>{})
	REFLECT_CONTAINER_PROPERTY(Layer, m_DeadGameObjects, "vector<class GameObject*>", Engine::EPropertyType::Array, &Layer_m_DeadGameObjects_Root_ContainerData, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(Layer)
IMPLEMENT_CLASS_EX(Layer, "Engine::Layer", "Engine::Base")

#pragma endregion // CLASS: Engine::Layer

#pragma region CLASS: Engine::GameObject
BEGIN_METADATA(GameObject, m_ID)
	CATEGORY("PROP_INFORMATION")
	READONLY
	NOSERIALIZE
END_METADATA

BEGIN_METADATA(GameObject, m_Index)
	CATEGORY("PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(GameObject, m_LayerIndex)
	CATEGORY("PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(GameObject, m_Name)
	EDITABLE
	"PROP_NAME"
END_METADATA

BEGIN_METADATA(GameObject, m_Flags)
	EDITABLE
	"PROP_BITFLAG"
END_METADATA

BEGIN_METADATA(GameObject, m_TagSet)
	EDITABLE
	"PROP_TAGS"
END_METADATA

DECLARE_CONTAINER_INFO(GameObject, m_TagSet_Root, "wstring", Engine::EPropertyType::Wstring, Engine::SetAccessor<unordered_set<wstring>, wstring>::Get())
BEGIN_METADATA(GameObject, m_Components)
	NAME("PROP_COMPONENTS")
END_METADATA

DECLARE_CONTAINER_INFO(GameObject, m_Components_Root, "Engine::Component", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<Component*>, Component*>::Get())
DECLARE_CONTAINER_INFO(GameObject, m_Childs_Root, "Engine::GameObject", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<GameObject*>, GameObject*>::Get())
BEGIN_PROPERTIES(GameObject)
	REFLECT_PROPERTY(GameObject, m_ID, "uint64", Engine::EPropertyType::UInt64, std::span<const Engine::MetadataEntry>{GameObject_m_ID_Meta})
	REFLECT_PROPERTY(GameObject, m_Index, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{GameObject_m_Index_Meta})
	REFLECT_PROPERTY(GameObject, m_LayerIndex, "uint32", Engine::EPropertyType::UInt32, std::span<const Engine::MetadataEntry>{GameObject_m_LayerIndex_Meta})
	REFLECT_PROPERTY(GameObject, m_Name, "wstring", Engine::EPropertyType::Wstring, std::span<const Engine::MetadataEntry>{GameObject_m_Name_Meta})
	REFLECT_PROPERTY(GameObject, m_Flags, "EObjectFlag", Engine::EPropertyType::BitFlag, std::span<const Engine::MetadataEntry>{GameObject_m_Flags_Meta})
	REFLECT_CONTAINER_PROPERTY(GameObject, m_TagSet, "unordered_set<wstring>", Engine::EPropertyType::Set, &GameObject_m_TagSet_Root_ContainerData, std::span<const Engine::MetadataEntry>{GameObject_m_TagSet_Meta})
	REFLECT_CONTAINER_PROPERTY(GameObject, m_Components, "vector<Component*>", Engine::EPropertyType::Array, &GameObject_m_Components_Root_ContainerData, std::span<const Engine::MetadataEntry>{GameObject_m_Components_Meta})
	REFLECT_CONTAINER_PROPERTY(GameObject, m_Childs, "vector<GameObject*>", Engine::EPropertyType::Array, &GameObject_m_Childs_Root_ContainerData, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(GameObject)
IMPLEMENT_CLASS_EX(GameObject, "Engine::GameObject", "Engine::Base")

#pragma endregion // CLASS: Engine::GameObject

#pragma region CLASS: Engine::Scene
DECLARE_CONTAINER_INFO(Scene, m_Layers_Root, "class Layer", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<class Layer*>, class Layer*>::Get())
BEGIN_PROPERTIES(Scene)
	REFLECT_PROPERTY(Scene, m_Flags, "ESceneFlags", Engine::EPropertyType::BitFlag, std::span<const Engine::MetadataEntry>{})
	REFLECT_PROPERTY(Scene, m_Name, "wstring", Engine::EPropertyType::Wstring, std::span<const Engine::MetadataEntry>{})
	REFLECT_CONTAINER_PROPERTY(Scene, m_Layers, "vector<class Layer*>", Engine::EPropertyType::Array, &Scene_m_Layers_Root_ContainerData, std::span<const Engine::MetadataEntry>{})
END_PROPERTIES
EMPTY_FUNCTIONS(Scene)
IMPLEMENT_CLASS_EX(Scene, "Engine::Scene", "Engine::Base")

#pragma endregion // CLASS: Engine::Scene

#pragma endregion

#pragma pop_macro("new")
