// ==================================================
// 자동 생성된 리플렉션 코드 (수정하지 마세요!)
// ==================================================

#include "Engine_Includes.h"
#include <entt/entt.hpp>
#include "Core/Event/Public/BaseRaycaster.h"
#include "Core/Event/Public/DynamicEvent.h"
#include "Core/Event/Public/EventSystem.h"
#include "Core/Event/Public/GraphicRaycaster.h"
#include "Core/Public/CoreComponents.h"
#include "Core/Public/Interface/Component.h"
#include "Core/Public/RectTransform.h"
#include "Core/Public/Structs.h"
#include "Core/Public/Transform.h"
#include "Core/Public/Vertex.h"
#include "Physics/Components/Collider/Public/Box2DCollider.h"
#include "Physics/Components/Collider/Public/BoxCollider.h"
#include "Physics/Components/Collider/Public/Collider.h"
#include "Physics/Components/RigidBody/Public/RigidBody.h"
#include "Render/Camera/Public/Camera.h"
#include "Render/Components/Public/Animator.h"
#include "Render/Components/Public/LightSource.h"
#include "Render/Components/Public/MeshRenderer.h"
#include "Render/Components/Public/RenderComponent.h"
#include "Render/Components/Public/SkinnedMeshRenderer.h"
#include "Render/Components/Public/SpriteRenderer.h"
#include "Render/Components/Sky/Public/SkyLight.h"
#include "Render/Components/Sky/Public/SkyRenderer.h"
#include "Render/RHI/Public/RHIDefinitions.h"
#include "Render/Sampler/Public/SamplerDesc.h"
#include "Resource/Components/MeshFilter/Public/MeshFilter.h"
#include "Resource/Material/Public/Material.h"
#include "Resource/Material/Public/MaterialInstance.h"
#include "Resource/Material/Public/MaterialInterface.h"
#include "Resource/Model/Public/Animation.h"
#include "Resource/Model/Public/Bone.h"
#include "Resource/Model/Public/Mesh.h"
#include "Resource/Model/Public/Model.h"
#include "Resource/Model/Public/Skeleton.h"
#include "Resource/Public/Resource.h"
#include "Resource/Script/Public/Script.h"
#include "Resource/Shader/Public/Shader.h"
#include "Resource/Sprite/Public/Sprite.h"
#include "Resource/Texture/Public/Texture.h"
#include "UI/Public/UIButton.h"
#include "UI/Public/UICanvas.h"
#include "UI/Public/UIComponent.h"
#include "UI/Public/UIImage.h"
#include "UI/Public/UIRenderComponent.h"
#include "UI/Public/UISelectable.h"
#include "World/Layer/Public/Layer.h"
#include "World/Public/GameObject.h"
#include "World/Scene/Public/Scene.h"

namespace Engine {

void RegisterReflection_EnTT() 
{
    using namespace entt::literals;

    BEGIN_ENTT_REFLECT_ENUM(EEntityFlag)
        ENTT_ENUM_ENTRY(EEntityFlag, None)
        ENTT_ENUM_ENTRY(EEntityFlag, Active)
        ENTT_ENUM_ENTRY(EEntityFlag, Visible)
        ENTT_ENUM_ENTRY(EEntityFlag, Paused)
        ENTT_ENUM_ENTRY(EEntityFlag, Dead)
        ENTT_ENUM_ENTRY(EEntityFlag, Default)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EAlignment)
        ENTT_ENUM_ENTRY(EAlignment, TopLeft)
        ENTT_ENUM_ENTRY(EAlignment, TopCenter)
        ENTT_ENUM_ENTRY(EAlignment, TopRight)
        ENTT_ENUM_ENTRY(EAlignment, MiddleLeft)
        ENTT_ENUM_ENTRY(EAlignment, MiddleCenter)
        ENTT_ENUM_ENTRY(EAlignment, MiddleRight)
        ENTT_ENUM_ENTRY(EAlignment, BottomLeft)
        ENTT_ENUM_ENTRY(EAlignment, BottomCenter)
        ENTT_ENUM_ENTRY(EAlignment, BottomRight)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ERectSpace)
        ENTT_ENUM_ENTRY(ERectSpace, Local)
        ENTT_ENUM_ENTRY(ERectSpace, Screen)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ERectPivot)
        ENTT_ENUM_ENTRY(ERectPivot, Custorm)
        ENTT_ENUM_ENTRY(ERectPivot, TopLeft)
        ENTT_ENUM_ENTRY(ERectPivot, TopCenter)
        ENTT_ENUM_ENTRY(ERectPivot, TopRight)
        ENTT_ENUM_ENTRY(ERectPivot, MiddleLeft)
        ENTT_ENUM_ENTRY(ERectPivot, MiddleCenter)
        ENTT_ENUM_ENTRY(ERectPivot, MiddleRight)
        ENTT_ENUM_ENTRY(ERectPivot, BottomLeft)
        ENTT_ENUM_ENTRY(ERectPivot, BottomCenter)
        ENTT_ENUM_ENTRY(ERectPivot, BottomRight)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ERectAnchor)
        ENTT_ENUM_ENTRY(ERectAnchor, Custorm)
        ENTT_ENUM_ENTRY(ERectAnchor, TopLeft)
        ENTT_ENUM_ENTRY(ERectAnchor, TopCenter)
        ENTT_ENUM_ENTRY(ERectAnchor, TopRight)
        ENTT_ENUM_ENTRY(ERectAnchor, MiddleLeft)
        ENTT_ENUM_ENTRY(ERectAnchor, MiddleCenter)
        ENTT_ENUM_ENTRY(ERectAnchor, MiddleRight)
        ENTT_ENUM_ENTRY(ERectAnchor, BottomLeft)
        ENTT_ENUM_ENTRY(ERectAnchor, BottomCenter)
        ENTT_ENUM_ENTRY(ERectAnchor, BottomRight)
        ENTT_ENUM_ENTRY(ERectAnchor, StretchTop)
        ENTT_ENUM_ENTRY(ERectAnchor, StretchMiddle)
        ENTT_ENUM_ENTRY(ERectAnchor, StretchBottom)
        ENTT_ENUM_ENTRY(ERectAnchor, StretchLeft)
        ENTT_ENUM_ENTRY(ERectAnchor, StretchCenter)
        ENTT_ENUM_ENTRY(ERectAnchor, StretchRight)
        ENTT_ENUM_ENTRY(ERectAnchor, StretchFull)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ERectTransformFlags)
        ENTT_ENUM_ENTRY(ERectTransformFlags, None)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockPositionX)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockPositionY)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockPosition)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockWidth)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockHeight)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockSize)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockRotation)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockScale)
        ENTT_ENUM_ENTRY(ERectTransformFlags, IgnoreLayout)
        ENTT_ENUM_ENTRY(ERectTransformFlags, InheritAlpha)
        ENTT_ENUM_ENTRY(ERectTransformFlags, RaycastTarget)
        ENTT_ENUM_ENTRY(ERectTransformFlags, Culled)
        ENTT_ENUM_ENTRY(ERectTransformFlags, LockRatio)
        ENTT_ENUM_ENTRY(ERectTransformFlags, AllLocked)
        ENTT_ENUM_ENTRY(ERectTransformFlags, Default)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EColliderType)
        ENTT_ENUM_ENTRY(EColliderType, Box)
        ENTT_ENUM_ENTRY(EColliderType, Box2D)
        ENTT_ENUM_ENTRY(EColliderType, Sphere)
        ENTT_ENUM_ENTRY(EColliderType, Capsule)
        ENTT_ENUM_ENTRY(EColliderType, Mesh)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ELightType)
        ENTT_ENUM_ENTRY(ELightType, Point)
        ENTT_ENUM_ENTRY(ELightType, Directional)
        ENTT_ENUM_ENTRY(ELightType, Spot)
        ENTT_ENUM_ENTRY(ELightType, Sky)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EAttenuationMode)
        ENTT_ENUM_ENTRY(EAttenuationMode, Coefficients)
        ENTT_ENUM_ENTRY(EAttenuationMode, InverseSquare)
        ENTT_ENUM_ENTRY(EAttenuationMode, Disabled)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ELightFlags)
        ENTT_ENUM_ENTRY(ELightFlags, None)
        ENTT_ENUM_ENTRY(ELightFlags, CastShadows)
        ENTT_ENUM_ENTRY(ELightFlags, UseInForwardRendering)
        ENTT_ENUM_ENTRY(ELightFlags, UseInDeferredRendering)
        ENTT_ENUM_ENTRY(ELightFlags, Volumetric)
        ENTT_ENUM_ENTRY(ELightFlags, AffectDiffuse)
        ENTT_ENUM_ENTRY(ELightFlags, AffectSpecular)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EDrawMode)
        ENTT_ENUM_ENTRY(EDrawMode, Simple)
        ENTT_ENUM_ENTRY(EDrawMode, Sliced)
        ENTT_ENUM_ENTRY(EDrawMode, Tiled)
        ENTT_ENUM_ENTRY(EDrawMode, Filled)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ESpriteRenderMode)
        ENTT_ENUM_ENTRY(ESpriteRenderMode, World)
        ENTT_ENUM_ENTRY(ESpriteRenderMode, Billboard)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ESkyShape)
        ENTT_ENUM_ENTRY(ESkyShape, Sphere)
        ENTT_ENUM_ENTRY(ESkyShape, Cube)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EPipelineType)
        ENTT_ENUM_ENTRY(EPipelineType, Graphics)
        ENTT_ENUM_ENTRY(EPipelineType, Compute)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EBlendMode)
        ENTT_ENUM_ENTRY(EBlendMode, None)
        ENTT_ENUM_ENTRY(EBlendMode, Opaque)
        ENTT_ENUM_ENTRY(EBlendMode, AlphaBlend)
        ENTT_ENUM_ENTRY(EBlendMode, Additive)
        ENTT_ENUM_ENTRY(EBlendMode, NonPremultiplied)
        ENTT_ENUM_ENTRY(EBlendMode, Masked)
        ENTT_ENUM_ENTRY(EBlendMode, Forward)
        ENTT_ENUM_ENTRY(EBlendMode, Decal)
        ENTT_ENUM_ENTRY(EBlendMode, ALL)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EFillMode)
        ENTT_ENUM_ENTRY(EFillMode, Wireframe)
        ENTT_ENUM_ENTRY(EFillMode, Solid)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ECullMode)
        ENTT_ENUM_ENTRY(ECullMode, None)
        ENTT_ENUM_ENTRY(ECullMode, Front)
        ENTT_ENUM_ENTRY(ECullMode, Back)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EFrontFace)
        ENTT_ENUM_ENTRY(EFrontFace, Clockwise)
        ENTT_ENUM_ENTRY(EFrontFace, CounterClockwise)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EDepthMode)
        ENTT_ENUM_ENTRY(EDepthMode, None)
        ENTT_ENUM_ENTRY(EDepthMode, ReadOnly)
        ENTT_ENUM_ENTRY(EDepthMode, ReadWrite)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ETopology)
        ENTT_ENUM_ENTRY(ETopology, TriangleList)
        ENTT_ENUM_ENTRY(ETopology, TriangleStrip)
        ENTT_ENUM_ENTRY(ETopology, LineList)
        ENTT_ENUM_ENTRY(ETopology, LineStrip)
        ENTT_ENUM_ENTRY(ETopology, PointList)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ECompareOp)
        ENTT_ENUM_ENTRY(ECompareOp, Never)
        ENTT_ENUM_ENTRY(ECompareOp, Less)
        ENTT_ENUM_ENTRY(ECompareOp, Equal)
        ENTT_ENUM_ENTRY(ECompareOp, LessOrEqual)
        ENTT_ENUM_ENTRY(ECompareOp, Greater)
        ENTT_ENUM_ENTRY(ECompareOp, NotEqual)
        ENTT_ENUM_ENTRY(ECompareOp, GreaterOrEqual)
        ENTT_ENUM_ENTRY(ECompareOp, Always)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EBlendFactor)
        ENTT_ENUM_ENTRY(EBlendFactor, None)
        ENTT_ENUM_ENTRY(EBlendFactor, Zero)
        ENTT_ENUM_ENTRY(EBlendFactor, One)
        ENTT_ENUM_ENTRY(EBlendFactor, SrcColor)
        ENTT_ENUM_ENTRY(EBlendFactor, InvSrcColor)
        ENTT_ENUM_ENTRY(EBlendFactor, SrcAlpha)
        ENTT_ENUM_ENTRY(EBlendFactor, InvSrcAlpha)
        ENTT_ENUM_ENTRY(EBlendFactor, DstColor)
        ENTT_ENUM_ENTRY(EBlendFactor, InvDstColor)
        ENTT_ENUM_ENTRY(EBlendFactor, DstAlpha)
        ENTT_ENUM_ENTRY(EBlendFactor, InvDstAlpha)
        ENTT_ENUM_ENTRY(EBlendFactor, SrcAlphaSaturate)
        ENTT_ENUM_ENTRY(EBlendFactor, BlendColor)
        ENTT_ENUM_ENTRY(EBlendFactor, InvBlendColor)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EBlendOp)
        ENTT_ENUM_ENTRY(EBlendOp, None)
        ENTT_ENUM_ENTRY(EBlendOp, Add)
        ENTT_ENUM_ENTRY(EBlendOp, Subtract)
        ENTT_ENUM_ENTRY(EBlendOp, RevSubtract)
        ENTT_ENUM_ENTRY(EBlendOp, Min)
        ENTT_ENUM_ENTRY(EBlendOp, Max)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EColorChannel)
        ENTT_ENUM_ENTRY(EColorChannel, NONE)
        ENTT_ENUM_ENTRY(EColorChannel, R)
        ENTT_ENUM_ENTRY(EColorChannel, G)
        ENTT_ENUM_ENTRY(EColorChannel, B)
        ENTT_ENUM_ENTRY(EColorChannel, A)
        ENTT_ENUM_ENTRY(EColorChannel, RGB)
        ENTT_ENUM_ENTRY(EColorChannel, RGBA)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ESamplerFilter)
        ENTT_ENUM_ENTRY(ESamplerFilter, Point)
        ENTT_ENUM_ENTRY(ESamplerFilter, Linear)
        ENTT_ENUM_ENTRY(ESamplerFilter, Anisotropic)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ESamplerAddressMode)
        ENTT_ENUM_ENTRY(ESamplerAddressMode, Wrap)
        ENTT_ENUM_ENTRY(ESamplerAddressMode, Mirror)
        ENTT_ENUM_ENTRY(ESamplerAddressMode, Clamp)
        ENTT_ENUM_ENTRY(ESamplerAddressMode, Border)
        ENTT_ENUM_ENTRY(ESamplerAddressMode, MirrorOnce)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EPipelineOverrideFlag)
        ENTT_ENUM_ENTRY(EPipelineOverrideFlag, None)
        ENTT_ENUM_ENTRY(EPipelineOverrideFlag, BlendMode)
        ENTT_ENUM_ENTRY(EPipelineOverrideFlag, CullMode)
        ENTT_ENUM_ENTRY(EPipelineOverrideFlag, FillMode)
        ENTT_ENUM_ENTRY(EPipelineOverrideFlag, DepthMode)
        ENTT_ENUM_ENTRY(EPipelineOverrideFlag, DepthCompareOp)
        ENTT_ENUM_ENTRY(EPipelineOverrideFlag, Count)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EMaterialParameterType)
        ENTT_ENUM_ENTRY(EMaterialParameterType, Float)
        ENTT_ENUM_ENTRY(EMaterialParameterType, Float2)
        ENTT_ENUM_ENTRY(EMaterialParameterType, Float3)
        ENTT_ENUM_ENTRY(EMaterialParameterType, Float4)
        ENTT_ENUM_ENTRY(EMaterialParameterType, Int)
        ENTT_ENUM_ENTRY(EMaterialParameterType, Bool)
        ENTT_ENUM_ENTRY(EMaterialParameterType, Matrix)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EMeshFlag)
        ENTT_ENUM_ENTRY(EMeshFlag, None)
        ENTT_ENUM_ENTRY(EMeshFlag, HasPosition)
        ENTT_ENUM_ENTRY(EMeshFlag, HasNormal)
        ENTT_ENUM_ENTRY(EMeshFlag, HasTexCoord)
        ENTT_ENUM_ENTRY(EMeshFlag, HasTangent)
        ENTT_ENUM_ENTRY(EMeshFlag, HasBitangent)
        ENTT_ENUM_ENTRY(EMeshFlag, HasColor)
        ENTT_ENUM_ENTRY(EMeshFlag, Dynamic)
        ENTT_ENUM_ENTRY(EMeshFlag, KeepRawData)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EResourceType)
        ENTT_ENUM_ENTRY(EResourceType, Unknown)
        ENTT_ENUM_ENTRY(EResourceType, Texture)
        ENTT_ENUM_ENTRY(EResourceType, Sprite)
        ENTT_ENUM_ENTRY(EResourceType, Material)
        ENTT_ENUM_ENTRY(EResourceType, MaterialInstance)
        ENTT_ENUM_ENTRY(EResourceType, Shader)
        ENTT_ENUM_ENTRY(EResourceType, Mesh)
        ENTT_ENUM_ENTRY(EResourceType, Model)
        ENTT_ENUM_ENTRY(EResourceType, Animation)
        ENTT_ENUM_ENTRY(EResourceType, AudioClip)
        ENTT_ENUM_ENTRY(EResourceType, Skeleton)
        ENTT_ENUM_ENTRY(EResourceType, Prefab)
        ENTT_ENUM_ENTRY(EResourceType, Script)
        ENTT_ENUM_ENTRY(EResourceType, Scene)
        ENTT_ENUM_ENTRY(EResourceType, Save)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ECanvasRenderMode)
        ENTT_ENUM_ENTRY(ECanvasRenderMode, ScreenSpace)
        ENTT_ENUM_ENTRY(ECanvasRenderMode, WorldSpace)
        ENTT_ENUM_ENTRY(ECanvasRenderMode, ScreenSpaceCamera)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ECanvasLayoutSource)
        ENTT_ENUM_ENTRY(ECanvasLayoutSource, InheritParent)
        ENTT_ENUM_ENTRY(ECanvasLayoutSource, ReferenceResolution)
        ENTT_ENUM_ENTRY(ECanvasLayoutSource, ExternalOverride)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EUIScaleMode)
        ENTT_ENUM_ENTRY(EUIScaleMode, ConstantPixelSize)
        ENTT_ENUM_ENTRY(EUIScaleMode, ScaleWithScreenSize)
        ENTT_ENUM_ENTRY(EUIScaleMode, ConstantPhysicalSize)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ESelectionState)
        ENTT_ENUM_ENTRY(ESelectionState, Normal)
        ENTT_ENUM_ENTRY(ESelectionState, Hovered)
        ENTT_ENUM_ENTRY(ESelectionState, Pressed)
        ENTT_ENUM_ENTRY(ESelectionState, Disabled)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(ELayerFlags)
        ENTT_ENUM_ENTRY(ELayerFlags, None)
        ENTT_ENUM_ENTRY(ELayerFlags, Active)
        ENTT_ENUM_ENTRY(ELayerFlags, Visible)
        ENTT_ENUM_ENTRY(ELayerFlags, Default)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT_ENUM(EObjectFlag)
        ENTT_ENUM_ENTRY(EObjectFlag, None)
        ENTT_ENUM_ENTRY(EObjectFlag, Active)
        ENTT_ENUM_ENTRY(EObjectFlag, Visible)
        ENTT_ENUM_ENTRY(EObjectFlag, Paused)
        ENTT_ENUM_ENTRY(EObjectFlag, Dead)
        ENTT_ENUM_ENTRY(EObjectFlag, Default)
    END_ENTT_REFLECT_ENUM()

    BEGIN_ENTT_REFLECT(BaseRaycaster)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(DynamicEvent)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(EventSystem)
        .ctor<>()
        ENTT_PROPERTY(EventSystem, m_Raycasters)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(GraphicRaycaster)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(TagComponent)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(IDComponent)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(NameComponent)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(FlagComponent)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(TransformComponent)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(TransformComponent, Rotation, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(TransformComponent, Scale, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(WorldTransformComponent)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(HierarchyComponent)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(RectTransform)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_AnchoredPosition, "NAME(\"PROP_POSITION\"), EDITABLE, RANGE(), ONCHANGED(\"SetAnchoredPosition\", \"m_AnchoredPosition\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_Rotation, "EDITABLE, RANGE(), ONCHANGED(\"SetRotation\", \"m_Rotation\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_Size, "EDITABLE, RANGE(), ONCHANGED(\"SetSize\", \"m_Size\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_Scale, "EDITABLE, RANGE(), ONCHANGED(\"SetScale\", \"m_Scale\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_AnchorMin, "EDITABLE, RANGE(), CATEGORY(\"Anchor\"), ONCHANGED(\"SetAnchorMin\", \"m_AnchorMin\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_AnchorMax, "EDITABLE, RANGE(), CATEGORY(\"Anchor\"), ONCHANGED(\"SetAnchorMax\", \"m_AnchorMax\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_Pivot, "EDITABLE, RANGE(0.f, 1.f, 0.01f), ONCHANGED(\"SetPivot\", \"m_Pivot\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_Flags, "EDITABLE, ONCHANGED(\"SetFlags\", \"m_Flags\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_Matrix, "NAME(\"PROP_MATRIX\"), READONLY, NOSERIALIZE, CATEGORY(\"Details\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_WorldTransform, "NAME(\"PROP_WORLD_TRANSFORM\"), READONLY, NOSERIALIZE, CATEGORY(\"Details\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_AbsolutePosition, "NAME(\"PROP_ABSOLUTEPOSITION\"), READONLY, NOSERIALIZE, CATEGORY(\"Details\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_AbsoluteSize, "NAME(\"PROP_ABSOLUTESIZE\"), READONLY, NOSERIALIZE, CATEGORY(\"Details\")")
        ENTT_PROPERTY_WITH_ATTR(RectTransform, m_Ratio, "NAME(\"PROP_RATIO\"), READONLY, NOSERIALIZE, CATEGORY(\"Details\")")
        ENTT_FUNCTION(RectTransform, SetSize)
        ENTT_FUNCTION(RectTransform, SetAnchorMin)
        ENTT_FUNCTION(RectTransform, SetAnchorMax)
        ENTT_FUNCTION(RectTransform, SetAnchoredPosition)
        ENTT_FUNCTION(RectTransform, SetPivot)
        ENTT_FUNCTION(RectTransform, SetScale)
        ENTT_FUNCTION(RectTransform, SetRotation)
        ENTT_FUNCTION(RectTransform, SetFlags)
        ENTT_FUNCTION(RectTransform, SetAnchorPreset)
        ENTT_FUNCTION(RectTransform, SetPivotPreset)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(ComponentDesc)
        .ctor<>()
        ENTT_PROPERTY(ComponentDesc, Tag)
        ENTT_PROPERTY(ComponentDesc, Owner)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Component)
        .ctor<>()
        ENTT_PROPERTY(Component, m_Active)
        ENTT_PROPERTY(Component, m_Dirty)
        ENTT_PROPERTY(Component, m_Tag)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Box2DCollider)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Box2DCollider, m_Center, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(Box2DCollider, m_Extent, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(BoxCollider)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(BoxCollider, m_Center, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(BoxCollider, m_Extents, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Collider)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Collider, m_Type, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(RigidBody)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(RigidBody, m_Mass, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(RigidBody, m_UseGravity, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(RigidBody, m_GravityScale, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(RigidBody, m_LinearDamping, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(RigidBody, m_IsKinematic, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(RigidBody, m_Velocity, "READONLY")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Camera)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Camera, m_FOV, "EDITABLE, EDITCONDITION(\"m_IsPerspective\")")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_Near, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_Far, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_Aspect, "EDITABLE, EDITCONDITION(\"m_IsPerspective\")")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_OrthoSize, "EDITABLE, EDITCONDITION(\"!m_IsPerspective\")")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_IsPerspective, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_ProjMatrix, "READONLY")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_ViewMatrix, "READONLY")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_IsMainCamera, "EDITABLE, ONCHANGED(\"SetMainCamera\")")
        ENTT_PROPERTY_WITH_ATTR(Camera, m_CullingMask, "EDITABLE, CATEGORY(\"PROP_RENDER\")")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(AnimationState)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(AnimationState, Clip, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(AnimationState, Loop, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(AnimationState, PlaybackSpeed, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Animator)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Animator, m_Skeleton, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(Animator, m_States, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(LightSource)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_Type, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_Color, "EDITABLE, COLOR")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_Intensity, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_Range, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_AttenuationMode, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_AttenuationCoefficients, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_SpotInnerAngle, "EDITABLE, EDITCONDITION(\"m_Type\", ELightType::Spot, true)")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_SpotOuterAngle, "EDITABLE, EDITCONDITION(\"m_Type\", ELightType::Spot, true)")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_SpotFalloffExponent, "EDITABLE, EDITCONDITION(\"m_Type\", ELightType::Spot, true)")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_LightingLayerMask, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_ShadowRange, "EDITABLE, EDITCONDITION(\"m_Flags\", ELightFlags::CastShadows, false), CATEGORY(\"Shadow\"), RANGE(-FLT_MAX, FLT_MAX, 0.01f)")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_ShadowBias, "EDITABLE, EDITCONDITION(\"m_Flags\", ELightFlags::CastShadows, false), CATEGORY(\"Shadow\"), RANGE(-FLT_MAX, FLT_MAX, 0.001f)")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_ShadowSlopeBias, "EDITABLE, EDITCONDITION(\"m_Flags\", ELightFlags::CastShadows, false), CATEGORY(\"Shadow\"), RANGE(-FLT_MAX, FLT_MAX, 0.1f)")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_ShadowNormalBias, "EDITABLE, EDITCONDITION(\"m_Flags\", ELightFlags::CastShadows, false), CATEGORY(\"Shadow\"), RANGE(-FLT_MAX, FLT_MAX, 0.001f)")
        ENTT_PROPERTY_WITH_ATTR(LightSource, m_Flags, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(MeshRenderer)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(RenderComponent)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(RenderComponent, m_DrawShadow, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(RenderComponent, m_ReceiveShadow, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(RenderComponent, m_Materials, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(RenderComponent, m_VisibilityChannel, "EDITABLE, CATEGORY(\"PROP_RENDER\")")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(SkinnedMeshRenderer)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(SpriteRenderer)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(SpriteRenderer, m_Tiling, "EDITABLE, DEFAULT(vec2(1.f, 1.f))")
        ENTT_PROPERTY_WITH_ATTR(SpriteRenderer, m_Mesh, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SpriteRenderer, m_Sprite, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SpriteRenderer, m_RenderMode, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SpriteRenderer, m_CachedSpriteVersion, "CATEGORY(\"DETAIL\"), READONLY, NOSERIALIZE")
        ENTT_PROPERTY_WITH_ATTR(SpriteRenderer, m_DrawMode, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(SkyLight)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(SkyLight, m_GroundColor, "EDITABLE, COLOR")
        ENTT_PROPERTY_WITH_ATTR(SkyLight, m_IndirectIntensity, "EDITABLE")
        ENTT_PROPERTY(SkyLight, m_Direction)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(SkyRenderer)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_Shape, "EDITABLE, CATEGORY(\"Shape\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_ZenithColor, "EDITABLE, COLOR, CATEGORY(\"Atmosphere\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_HorizonColor, "EDITABLE, COLOR, CATEGORY(\"Atmosphere\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_GroundColor, "EDITABLE, COLOR, CATEGORY(\"Atmosphere\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_HorizonBlend, "EDITABLE, CATEGORY(\"Atmosphere\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_SkyIntensity, "EDITABLE, CATEGORY(\"Atmosphere\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_SunDirection, "EDITABLE, CATEGORY(\"Sun\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_SunColor, "EDITABLE, COLOR, CATEGORY(\"Sun\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_SunIntensity, "EDITABLE, CATEGORY(\"Sun\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_SunSize, "EDITABLE, CATEGORY(\"Sun\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_SphereStacks, "EDITABLE, EDITCONDITION(\"m_Shape\", ESkyShape::Sphere, true), CATEGORY(\"Shape\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_SphereSlices, "EDITABLE, EDITCONDITION(\"m_Shape\", ESkyShape::Sphere, true), CATEGORY(\"Shape\")")
        ENTT_PROPERTY_WITH_ATTR(SkyRenderer, m_Mesh, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(tagBlendState)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(tagBlendState, DstColor, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(tagBlendState, ColorBlendOp, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(tagBlendState, SrcAlpha, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(tagBlendState, DstAlpha, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(tagBlendState, AlphaBlendOp, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(tagBlendState, ColorWriteMask, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(tagBlendState, Enable, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(tagBlendState, EnableColorWriteMask, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(SamplerDesc)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(SamplerDesc, MagFilter, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SamplerDesc, MipFilter, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SamplerDesc, AddressU, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SamplerDesc, AddressV, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SamplerDesc, AddressW, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SamplerDesc, MaxAnisotropy, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(SamplerDesc, BorderColor, "EDITABLE, COLOR")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(MeshFilter)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(MeshFilter, m_MeshHandle, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Material)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(MaterialInstance)
        .ctor<>()
        ENTT_PROPERTY(MaterialInstance, m_BaseMaterialHandle)
        ENTT_PROPERTY(MaterialInstance, m_OverrideFlags)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(MaterialTextureBinding)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(MaterialTextureBinding, name, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(MaterialTextureBinding, texture, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(MaterialTextureBinding, hasCustomSampler, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(MaterialTextureBinding, samplerDesc, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(MaterialParameter)
        .ctor<>()
        ENTT_PROPERTY(MaterialParameter, data)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(MaterialInterface)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_BlendMode, "EDITABLE, CATEGORY(L\"Pipeline\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_CullMode, "EDITABLE, CATEGORY(L\"Pipeline\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_FrontFace, "EDITABLE, CATEGORY(L\"Pipeline\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_FillMode, "EDITABLE, CATEGORY(L\"Pipeline\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_DepthMode, "EDITABLE, CATEGORY(L\"Pipeline\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_DepthCompareOp, "EDITABLE, CATEGORY(L\"Pipeline\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_VertexShaderHandle, "EDITABLE, CATEGORY(L\"Shader\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_PixelShaderHandle, "EDITABLE, CATEGORY(L\"Shader\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_Parameters, "EDITABLE, CATEGORY(L\"Parameter\")")
        ENTT_PROPERTY_WITH_ATTR(MaterialInterface, m_TextureBindings, "EDITABLE, CATEGORY(\"Texture\")")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Animation)
        .ctor<>()
        ENTT_PROPERTY(Animation, m_Name)
        ENTT_PROPERTY(Animation, m_Duration)
        ENTT_PROPERTY(Animation, m_TicksPerSecond)
        ENTT_PROPERTY(Animation, m_Tracks)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Bone)
        .ctor<>()
        ENTT_PROPERTY(Bone, OffsetMatrix)
        ENTT_PROPERTY(Bone, LocalTransform)
        ENTT_PROPERTY(Bone, ParentIndex)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Mesh)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Mesh, m_Topology, "CATEGORY(L\"PROP_INFORMATION\"), READONLY")
        ENTT_PROPERTY_WITH_ATTR(Mesh, m_IndexCount, "CATEGORY(L\"PROP_INFORMATION\"), READONLY")
        ENTT_PROPERTY_WITH_ATTR(Mesh, m_BoundingBoxMin, "CATEGORY(L\"PROP_INFORMATION\"), READONLY")
        ENTT_PROPERTY_WITH_ATTR(Mesh, m_BoundingBoxMax, "CATEGORY(L\"PROP_INFORMATION\"), READONLY")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Model)
        .ctor<>()
        ENTT_PROPERTY(Model, m_Meshes)
        ENTT_PROPERTY(Model, m_Materials)
        ENTT_PROPERTY(Model, m_Skeleton)
        ENTT_PROPERTY(Model, m_Animations)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Skeleton)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Skeleton, m_Bones, "CATEGORY(\"PROP_BONE\")")
        ENTT_PROPERTY_WITH_ATTR(Skeleton, m_BoneMap, "CATEGORY(\"PROP_BONE\")")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(ResourceBinaryHeader)
        .ctor<>()
        ENTT_PROPERTY(ResourceBinaryHeader, ResourceType)
        ENTT_PROPERTY(ResourceBinaryHeader, Version)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Resource)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Resource, m_Version, "READONLY")
        ENTT_PROPERTY_WITH_ATTR(Resource, m_ResourceType, "READONLY")
        ENTT_PROPERTY_WITH_ATTR(Resource, m_Key, "READONLY")
        ENTT_PROPERTY_WITH_ATTR(Resource, m_Path, "READONLY")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Script)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Shader)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Shader, m_ShaderType, "READONLY")
        ENTT_PROPERTY_WITH_ATTR(Shader, m_SpirvPath, "READONLY")
        ENTT_PROPERTY(Shader, m_EntryPoint)
        ENTT_PROPERTY(Shader, m_NumSamplers)
        ENTT_PROPERTY(Shader, m_NumStorageTextures)
        ENTT_PROPERTY(Shader, m_NumStorageBuffers)
        ENTT_PROPERTY(Shader, m_NumUniformBuffers)
        ENTT_PROPERTY_WITH_ATTR(Shader, m_RHIShader, "NOSERIALIZE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Sprite)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(Sprite, m_Texture, "READONLY")
        ENTT_PROPERTY_WITH_ATTR(Sprite, m_Region, "READONLY")
        ENTT_PROPERTY_WITH_ATTR(Sprite, m_Pivot, "DEFAULT(vec2(0.5f, 0.5f))")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(TextureBinaryHeader)
        .ctor<>()
        ENTT_PROPERTY(TextureBinaryHeader, Height)
        ENTT_PROPERTY(TextureBinaryHeader, Depth)
        ENTT_PROPERTY(TextureBinaryHeader, MipLevels)
        ENTT_PROPERTY(TextureBinaryHeader, ArraySize)
        ENTT_PROPERTY(TextureBinaryHeader, DataSize)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Texture)
        .ctor<>()
        ENTT_PROPERTY(Texture, m_PixelPerUnit)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(UIButton)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(UICanvas)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_RenderMode, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_IsLayoutRoot, "EDITABLE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_LayoutSource, "EDITABLE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_ReferenceResolution, "EDITABLE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_ScaleMode, "EDITABLE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_MatchWidthOrHeight, "EDITABLE, RANGE(0.f, 1.f, 0.01f), CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_EffectiveLayoutSize, "READONLY, NOSERIALIZE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_ExternalLayoutSize, "NOSERIALIZE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_ExternalOverrideEnabled, "NOSERIALIZE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_ExternalOwnerToken, "NOSERIALIZE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_LayoutDirty, "READONLY, NOSERIALIZE, CATEGORY(\"Layout\")")
        ENTT_PROPERTY_WITH_ATTR(UICanvas, m_LayoutVersion, "READONLY, NOSERIALIZE, CATEGORY(\"Layout\")")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(UIComponent)
        .ctor<>()
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(UIImage)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(UIImage, m_Tiling, "EDITABLE, RANGE()")
        ENTT_PROPERTY_WITH_ATTR(UIImage, m_Offset, "EDITABLE, RANGE()")
        ENTT_PROPERTY_WITH_ATTR(UIImage, m_SpriteHandle, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(UIRenderComponent)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(UIRenderComponent, m_Color, "EDITABLE, COLOR()")
        ENTT_PROPERTY_WITH_ATTR(UIRenderComponent, m_VisibilityChannel, "EDITABLE, CATEGORY(\"PROP_RENDER\")")
        ENTT_PROPERTY_WITH_ATTR(UIRenderComponent, m_Material, "EDITABLE")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(UISelectable)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(UISelectable, m_Interactable, "EDITABLE")
        ENTT_PROPERTY_WITH_ATTR(UISelectable, m_NormalColor, "EDITABLE, COLOR()")
        ENTT_PROPERTY_WITH_ATTR(UISelectable, m_HoveredColor, "EDITABLE, COLOR()")
        ENTT_PROPERTY_WITH_ATTR(UISelectable, m_PressedColor, "EDITABLE, COLOR()")
        ENTT_PROPERTY_WITH_ATTR(UISelectable, m_DisabledColor, "EDITABLE, COLOR()")
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Layer)
        .ctor<>()
        ENTT_PROPERTY(Layer, m_Index)
        ENTT_PROPERTY(Layer, m_Name)
        ENTT_PROPERTY(Layer, m_Flags)
        ENTT_PROPERTY(Layer, m_GameObjects)
        ENTT_PROPERTY(Layer, m_DeadGameObjects)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(GameObject)
        .ctor<>()
        ENTT_PROPERTY_WITH_ATTR(GameObject, m_ID, "CATEGORY(\"PROP_INFORMATION\"), READONLY, NOSERIALIZE")
        ENTT_PROPERTY_WITH_ATTR(GameObject, m_Index, "CATEGORY(\"PROP_INFORMATION\"), READONLY")
        ENTT_PROPERTY_WITH_ATTR(GameObject, m_LayerIndex, "CATEGORY(\"PROP_INFORMATION\"), READONLY")
        ENTT_PROPERTY_WITH_ATTR(GameObject, m_Name, "EDITABLE, \"PROP_NAME\"")
        ENTT_PROPERTY_WITH_ATTR(GameObject, m_Flags, "EDITABLE, \"PROP_BITFLAG\"")
        ENTT_PROPERTY_WITH_ATTR(GameObject, m_TagSet, "EDITABLE, \"PROP_TAGS\"")
        ENTT_PROPERTY_WITH_ATTR(GameObject, m_Components, "NAME(\"PROP_COMPONENTS\")")
        ENTT_PROPERTY(GameObject, m_Childs)
    END_ENTT_REFLECT()

    BEGIN_ENTT_REFLECT(Scene)
        .ctor<>()
        ENTT_PROPERTY(Scene, m_Flags)
        ENTT_PROPERTY(Scene, m_Name)
    END_ENTT_REFLECT()

}

} // namespace Engine

