// Auto-generated by ReflectionGenerator.py
#include "Core/Public/Engine_Includes.h"
#include "Core/Reflection/Public/ReflectionMacro.h"
#include "Core/Reflection/Public/ReflectionContainers.h"

// [Header Includes]
#include "Core/Public/Component.h"
#include "Core/Public/Structs.h"
#include "Core/Public/Transform.h"
#include "Physics/Components/Collider/Public/Box2DCollider.h"
#include "Physics/Components/Collider/Public/BoxCollider.h"
#include "Physics/Components/Collider/Public/Collider.h"
#include "Render/Camera/Public/Camera.h"
#include "Render/Components/Public/MeshRenderer.h"
#include "Render/Components/Public/RenderComponent.h"
#include "Render/Components/Public/SpriteRenderer.h"
#include "Render/RHI/Public/RHIDefinitions.h"
#include "Resource/Components/MeshFilter/Public/MeshFilter.h"
#include "Resource/Material/Public/Material.h"
#include "Resource/Material/Public/MaterialInstance.h"
#include "Resource/Material/Public/MaterialInterface.h"
#include "Resource/Mesh/Public/Mesh.h"
#include "Resource/Model/Public/Model.h"
#include "Resource/Model/Public/Skeleton.h"
#include "Resource/Public/Resource.h"
#include "Resource/Shader/Public/Shader.h"
#include "Resource/Sprite/Public/Sprite.h"
#include "Resource/Texture/Public/Texture.h"
#include "UI/Button/Public/Button.h"
#include "UI/Public/UIComponent.h"
#include "World/Public/GameObject.h"

namespace Engine {

#pragma push_macro("new")
#undef new

// ==========================================================
// [ENUM REFLECTIONS]
// ==========================================================
#pragma region EnumReflections
// Enum: ETransformFlag
BEGIN_ENUM(ETransformFlag)
	REFLECT_ENUM_ENTRY(ETransformFlag, None)
	REFLECT_ENUM_ENTRY(ETransformFlag, InheritPosition)
	REFLECT_ENUM_ENTRY(ETransformFlag, InheritRotation)
	REFLECT_ENUM_ENTRY(ETransformFlag, InheritScale)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionX)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionY)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockPositionZ)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockPosition)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationX)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationY)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockRotationZ)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockRotation)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleX)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleY)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockScaleZ)
	REFLECT_ENUM_ENTRY(ETransformFlag, LockScale)
	REFLECT_ENUM_ENTRY(ETransformFlag, Static)
	REFLECT_ENUM_ENTRY(ETransformFlag, AllInherit)
	REFLECT_ENUM_ENTRY(ETransformFlag, AllLocked)
	REFLECT_ENUM_ENTRY(ETransformFlag, Default)
END_ENUM_REFLECT(ETransformFlag)
// Enum: EDrawMode
BEGIN_ENUM(EDrawMode)
	REFLECT_ENUM_ENTRY(EDrawMode, Simple)
	REFLECT_ENUM_ENTRY(EDrawMode, Sliced)
	REFLECT_ENUM_ENTRY(EDrawMode, Tiled)
	REFLECT_ENUM_ENTRY(EDrawMode, Filled)
END_ENUM_REFLECT(EDrawMode)
// Enum: EPipelineType
BEGIN_ENUM(EPipelineType)
	REFLECT_ENUM_ENTRY(EPipelineType, Graphics)
	REFLECT_ENUM_ENTRY(EPipelineType, Compute)
END_ENUM_REFLECT(EPipelineType)

// Enum: EBlendMode
BEGIN_ENUM(EBlendMode)
	REFLECT_ENUM_ENTRY(EBlendMode, Opaque)
	REFLECT_ENUM_ENTRY(EBlendMode, AlphaBlend)
	REFLECT_ENUM_ENTRY(EBlendMode, Additive)
	REFLECT_ENUM_ENTRY(EBlendMode, NonPremultiplied)
	REFLECT_ENUM_ENTRY(EBlendMode, Masked)
END_ENUM_REFLECT(EBlendMode)

// Enum: EFillMode
BEGIN_ENUM(EFillMode)
	REFLECT_ENUM_ENTRY(EFillMode, Wireframe)
	REFLECT_ENUM_ENTRY(EFillMode, Solid)
END_ENUM_REFLECT(EFillMode)

// Enum: ECullMode
BEGIN_ENUM(ECullMode)
	REFLECT_ENUM_ENTRY(ECullMode, None)
	REFLECT_ENUM_ENTRY(ECullMode, Front)
	REFLECT_ENUM_ENTRY(ECullMode, Back)
END_ENUM_REFLECT(ECullMode)

// Enum: EFrontFace
BEGIN_ENUM(EFrontFace)
	REFLECT_ENUM_ENTRY(EFrontFace, Clockwise)
	REFLECT_ENUM_ENTRY(EFrontFace, CounterClockwise)
END_ENUM_REFLECT(EFrontFace)

// Enum: EDepthMode
BEGIN_ENUM(EDepthMode)
	REFLECT_ENUM_ENTRY(EDepthMode, None)
	REFLECT_ENUM_ENTRY(EDepthMode, ReadOnly)
	REFLECT_ENUM_ENTRY(EDepthMode, ReadWrite)
END_ENUM_REFLECT(EDepthMode)

// Enum: ETopology
BEGIN_ENUM(ETopology)
	REFLECT_ENUM_ENTRY(ETopology, TriangleList)
	REFLECT_ENUM_ENTRY(ETopology, TriangleStrip)
	REFLECT_ENUM_ENTRY(ETopology, LineList)
	REFLECT_ENUM_ENTRY(ETopology, LineStrip)
	REFLECT_ENUM_ENTRY(ETopology, PointList)
END_ENUM_REFLECT(ETopology)

// Enum: ECompareOp
BEGIN_ENUM(ECompareOp)
	REFLECT_ENUM_ENTRY(ECompareOp, Never)
	REFLECT_ENUM_ENTRY(ECompareOp, Less)
	REFLECT_ENUM_ENTRY(ECompareOp, Equal)
	REFLECT_ENUM_ENTRY(ECompareOp, LessOrEqual)
	REFLECT_ENUM_ENTRY(ECompareOp, Greater)
	REFLECT_ENUM_ENTRY(ECompareOp, NotEqual)
	REFLECT_ENUM_ENTRY(ECompareOp, GreaterOrEqual)
	REFLECT_ENUM_ENTRY(ECompareOp, Always)
END_ENUM_REFLECT(ECompareOp)
// Enum: EPipelineOverrideFlag
BEGIN_ENUM(EPipelineOverrideFlag)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, None)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, BlendMode)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, CullMode)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, FillMode)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, DepthMode)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, DepthCompareOp)
	REFLECT_ENUM_ENTRY(EPipelineOverrideFlag, Count)
END_ENUM_REFLECT(EPipelineOverrideFlag)
// Enum: EMaterialParameterType
BEGIN_ENUM(EMaterialParameterType)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Float)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Float2)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Float3)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Float4)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Int)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Bool)
	REFLECT_ENUM_ENTRY(EMaterialParameterType, Matrix)
END_ENUM_REFLECT(EMaterialParameterType)
// Enum: EObjectFlag
BEGIN_ENUM(EObjectFlag)
	REFLECT_ENUM_ENTRY(EObjectFlag, None)
	REFLECT_ENUM_ENTRY(EObjectFlag, Active)
	REFLECT_ENUM_ENTRY(EObjectFlag, Visible)
	REFLECT_ENUM_ENTRY(EObjectFlag, Paused)
	REFLECT_ENUM_ENTRY(EObjectFlag, Dead)
	REFLECT_ENUM_ENTRY(EObjectFlag, Default)
END_ENUM_REFLECT(EObjectFlag)

#pragma endregion

#pragma region ClassStructReflections
// ==========================================================
// [CLASS/STRUCT REFLECTIONS]
// ==========================================================
#pragma region STRUCT: tagComponentDesc
BEGIN_PROPERTIES(tagComponentDesc)
	REFLECT_PROPERTY(tagComponentDesc, Active, "bool", Engine::EPropertyType::Bool, {})
	REFLECT_PROPERTY(tagComponentDesc, Tag, "wstring", Engine::EPropertyType::Wstring, {})
	REFLECT_PROPERTY(tagComponentDesc, Owner, "class GameObject", Engine::EPropertyType::Object, {})
END_PROPERTIES

EMPTY_FUNCTIONS(tagComponentDesc)

IMPLEMENT_CLASS(tagComponentDesc, None)

#pragma endregion // STRUCT: tagComponentDesc

#pragma region CLASS: Component
EMPTY_PROPERTIES(Component)

EMPTY_FUNCTIONS(Component)

IMPLEMENT_CLASS(Component, Base)

#pragma endregion // CLASS: Component

#pragma region STRUCT: AABB
BEGIN_PROPERTIES(AABB)
	REFLECT_PROPERTY(AABB, Min, "vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(AABB, Max, "vec3", Engine::EPropertyType::Vector3, {})
END_PROPERTIES

EMPTY_FUNCTIONS(AABB)

IMPLEMENT_CLASS(AABB, None)

#pragma endregion // STRUCT: AABB

#pragma region STRUCT: Rect
BEGIN_PROPERTIES(Rect)
	REFLECT_PROPERTY(Rect, Left, "f32", Engine::EPropertyType::F32, {})
	REFLECT_PROPERTY(Rect, Top, "f32", Engine::EPropertyType::F32, {})
	REFLECT_PROPERTY(Rect, Width, "f32", Engine::EPropertyType::F32, {})
	REFLECT_PROPERTY(Rect, Height, "f32", Engine::EPropertyType::F32, {})
END_PROPERTIES

EMPTY_FUNCTIONS(Rect)

IMPLEMENT_CLASS(Rect, None)

#pragma endregion // STRUCT: Rect

#pragma region STRUCT: Vertex
BEGIN_PROPERTIES(Vertex)
	REFLECT_PROPERTY(Vertex, position, "glm::vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(Vertex, normal, "glm::vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(Vertex, texCoord, "glm::vec2", Engine::EPropertyType::Vector2, {})
	REFLECT_PROPERTY(Vertex, tangent, "glm::vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(Vertex, bitangent, "glm::vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(Vertex, color, "glm::vec4", Engine::EPropertyType::Vector4, {})
END_PROPERTIES

EMPTY_FUNCTIONS(Vertex)

IMPLEMENT_CLASS(Vertex, None)

#pragma endregion // STRUCT: Vertex

#pragma region STRUCT: tagTransformDesc
BEGIN_PROPERTIES(tagTransformDesc)
	REFLECT_PROPERTY(tagTransformDesc, Position, "vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(tagTransformDesc, Rotation, "vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(tagTransformDesc, Scale, "vec3", Engine::EPropertyType::Vector3, {})
END_PROPERTIES

EMPTY_FUNCTIONS(tagTransformDesc)

IMPLEMENT_CLASS(tagTransformDesc, None)

#pragma endregion // STRUCT: tagTransformDesc

#pragma region CLASS: Transform
BEGIN_METADATA(Transform, m_LocalMatrix)
	NAME("PROP_LOCALMATRIX")
	READONLY
END_METADATA

BEGIN_METADATA(Transform, m_WorldMatrix)
	NAME("PROP_WORLDMATRIX")
	READONLY
END_METADATA

BEGIN_METADATA(Transform, m_Flags)
	NAME("PROP_BITFLAG")
END_METADATA

BEGIN_PROPERTIES(Transform)
	REFLECT_PROPERTY(Transform, m_Position, "vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(Transform, m_Rotation, "quat", Engine::EPropertyType::Quaternion, {})
	REFLECT_PROPERTY(Transform, m_Scale, "vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(Transform, m_LocalMatrix, "mat4", Engine::EPropertyType::Matrix4, Transform_m_LocalMatrix_Meta)
	REFLECT_PROPERTY(Transform, m_WorldMatrix, "mat4", Engine::EPropertyType::Matrix4, Transform_m_WorldMatrix_Meta)
	REFLECT_PROPERTY(Transform, m_Flags, "ETransformFlag", Engine::EPropertyType::Enum, Transform_m_Flags_Meta)
END_PROPERTIES

EMPTY_FUNCTIONS(Transform)

IMPLEMENT_CLASS(Transform, Component)

#pragma endregion // CLASS: Transform

#pragma region CLASS: Box2DCollider
BEGIN_PROPERTIES(Box2DCollider)
	REFLECT_PROPERTY(Box2DCollider, m_Center, "vec2", Engine::EPropertyType::Vector2, {})
	REFLECT_PROPERTY(Box2DCollider, m_Extent, "vec2", Engine::EPropertyType::Vector2, {})
END_PROPERTIES

EMPTY_FUNCTIONS(Box2DCollider)

IMPLEMENT_CLASS(Box2DCollider, Collider)

#pragma endregion // CLASS: Box2DCollider

#pragma region CLASS: BoxCollider
BEGIN_PROPERTIES(BoxCollider)
	REFLECT_PROPERTY(BoxCollider, m_Center, "vec3", Engine::EPropertyType::Vector3, {})
	REFLECT_PROPERTY(BoxCollider, m_Extents, "vec3", Engine::EPropertyType::Vector3, {})
END_PROPERTIES

EMPTY_FUNCTIONS(BoxCollider)

IMPLEMENT_CLASS(BoxCollider, Collider)

#pragma endregion // CLASS: BoxCollider

#pragma region CLASS: Collider
BEGIN_PROPERTIES(Collider)
	REFLECT_PROPERTY(Collider, m_DrawCollider, "bool", Engine::EPropertyType::Bool, {})
END_PROPERTIES

EMPTY_FUNCTIONS(Collider)

IMPLEMENT_CLASS(Collider, Component)

#pragma endregion // CLASS: Collider

#pragma region CLASS: Camera
BEGIN_METADATA(Camera, m_FOV)
	EDITCONDITION("m_IsPerspective")
END_METADATA

BEGIN_METADATA(Camera, m_Aspect)
	EDITCONDITION("m_IsPerspective")
END_METADATA

BEGIN_METADATA(Camera, m_OrthoSize)
	EDITCONDITION("!m_IsPerspective")
END_METADATA

BEGIN_METADATA(Camera, m_ProjMatrix)
	READONLY
END_METADATA

BEGIN_METADATA(Camera, m_ViewMatrix)
	READONLY
END_METADATA

BEGIN_PROPERTIES(Camera)
	REFLECT_PROPERTY(Camera, m_FOV, "f32", Engine::EPropertyType::F32, Camera_m_FOV_Meta)
	REFLECT_PROPERTY(Camera, m_Near, "f32", Engine::EPropertyType::F32, {})
	REFLECT_PROPERTY(Camera, m_Far, "f32", Engine::EPropertyType::F32, {})
	REFLECT_PROPERTY(Camera, m_Aspect, "f32", Engine::EPropertyType::F32, Camera_m_Aspect_Meta)
	REFLECT_PROPERTY(Camera, m_OrthoSize, "f32", Engine::EPropertyType::F32, Camera_m_OrthoSize_Meta)
	REFLECT_PROPERTY(Camera, m_IsPerspective, "bool", Engine::EPropertyType::Bool, {})
	REFLECT_PROPERTY(Camera, m_ProjMatrix, "glm::mat4", Engine::EPropertyType::Matrix4, Camera_m_ProjMatrix_Meta)
	REFLECT_PROPERTY(Camera, m_ViewMatrix, "glm::mat4", Engine::EPropertyType::Matrix4, Camera_m_ViewMatrix_Meta)
END_PROPERTIES

EMPTY_FUNCTIONS(Camera)

IMPLEMENT_CLASS(Camera, Component)

#pragma endregion // CLASS: Camera

#pragma region CLASS: MeshRenderer
EMPTY_PROPERTIES(MeshRenderer)

EMPTY_FUNCTIONS(MeshRenderer)

IMPLEMENT_CLASS(MeshRenderer, RenderComponent)

#pragma endregion // CLASS: MeshRenderer

#pragma region CLASS: RenderComponent
BEGIN_METADATA(RenderComponent, m_RenderPassID)
	CATEGORY("PROP_INFORMATION")
END_METADATA

DECLARE_CONTAINER_INFO(RenderComponent, m_MaterialInstances, "MaterialInstance*", Engine::EPropertyType::Object, Engine::LinearContainerAccessor<vector<MaterialInstance*>, MaterialInstance*>::Get())
BEGIN_PROPERTIES(RenderComponent)
	REFLECT_PROPERTY(RenderComponent, m_RenderPassID, "uint32", Engine::EPropertyType::UInt32, RenderComponent_m_RenderPassID_Meta)
	REFLECT_CONTAINER_PROPERTY(RenderComponent, m_MaterialInstances, "vector<MaterialInstance*>", Engine::EPropertyType::Array, &RenderComponent_m_MaterialInstances_ContainerData, {})
END_PROPERTIES

EMPTY_FUNCTIONS(RenderComponent)

IMPLEMENT_CLASS(RenderComponent, Component)

#pragma endregion // CLASS: RenderComponent

#pragma region CLASS: SpriteRenderer
BEGIN_METADATA(SpriteRenderer, m_Tiling)
	DEFAULT(vec2(1.f, 1.f))
END_METADATA

BEGIN_METADATA(SpriteRenderer, m_CachedSpriteVersion)
	CATEGORY("DETAIL")
	READONLY
END_METADATA

BEGIN_PROPERTIES(SpriteRenderer)
	REFLECT_PROPERTY(SpriteRenderer, m_Tiling, "vec2", Engine::EPropertyType::Vector2, SpriteRenderer_m_Tiling_Meta)
	REFLECT_PROPERTY(SpriteRenderer, m_Sprite, "Sprite", Engine::EPropertyType::Object, {})
	REFLECT_PROPERTY(SpriteRenderer, m_CachedSpriteVersion, "uint32", Engine::EPropertyType::UInt32, SpriteRenderer_m_CachedSpriteVersion_Meta)
	REFLECT_PROPERTY(SpriteRenderer, m_DrawMode, "EDrawMode", Engine::EPropertyType::Enum, {})
END_PROPERTIES

EMPTY_FUNCTIONS(SpriteRenderer)

IMPLEMENT_CLASS(SpriteRenderer, RenderComponent)

#pragma endregion // CLASS: SpriteRenderer

#pragma region CLASS: MeshFilter
BEGIN_PROPERTIES(MeshFilter)
	REFLECT_PROPERTY(MeshFilter, m_Mesh, "Mesh", Engine::EPropertyType::Object, {})
END_PROPERTIES

EMPTY_FUNCTIONS(MeshFilter)

IMPLEMENT_CLASS(MeshFilter, Component)

#pragma endregion // CLASS: MeshFilter

#pragma region CLASS: Material
EMPTY_PROPERTIES(Material)

EMPTY_FUNCTIONS(Material)

IMPLEMENT_CLASS(Material, MaterialInterface)

#pragma endregion // CLASS: Material

#pragma region CLASS: MaterialInstance
BEGIN_PROPERTIES(MaterialInstance)
	REFLECT_PROPERTY(MaterialInstance, m_BaseMaterial, "class Material", Engine::EPropertyType::Object, {})
	REFLECT_PROPERTY(MaterialInstance, m_OverrideFlags, "EPipelineOverrideFlag", Engine::EPropertyType::Enum, {})
END_PROPERTIES

EMPTY_FUNCTIONS(MaterialInstance)

IMPLEMENT_CLASS(MaterialInstance, MaterialInterface)

#pragma endregion // CLASS: MaterialInstance

#pragma region STRUCT: TextureSlot
BEGIN_PROPERTIES(TextureSlot)
	REFLECT_PROPERTY(TextureSlot, slot, "uint32", Engine::EPropertyType::UInt32, {})
	REFLECT_PROPERTY(TextureSlot, texture, "RHITexture", Engine::EPropertyType::Object, {})
	REFLECT_PROPERTY(TextureSlot, SamplerKey, "wstring", Engine::EPropertyType::Wstring, {})
END_PROPERTIES

EMPTY_FUNCTIONS(TextureSlot)

IMPLEMENT_CLASS(TextureSlot, None)

#pragma endregion // STRUCT: TextureSlot

#pragma region STRUCT: MaterialParameter
DECLARE_CONTAINER_INFO(MaterialParameter, data, "uint8", Engine::EPropertyType::UInt8, Engine::LinearContainerAccessor<vector<uint8>, uint8>::Get())
BEGIN_PROPERTIES(MaterialParameter)
	REFLECT_PROPERTY(MaterialParameter, type, "EMaterialParameterType", Engine::EPropertyType::Enum, {})
	REFLECT_CONTAINER_PROPERTY(MaterialParameter, data, "vector<uint8>", Engine::EPropertyType::Array, &MaterialParameter_data_ContainerData, {})
END_PROPERTIES

EMPTY_FUNCTIONS(MaterialParameter)

IMPLEMENT_CLASS(MaterialParameter, None)

#pragma endregion // STRUCT: MaterialParameter

#pragma region CLASS: MaterialInterface
BEGIN_METADATA(MaterialInterface, m_BlendMode)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_CullMode)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_FillMode)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_DepthMode)
	CATEGORY(L"Pipeline")
END_METADATA

BEGIN_METADATA(MaterialInterface, m_DepthCompareOp)
	CATEGORY(L"Pipeline")
END_METADATA

DECLARE_MAP_INFO(MaterialInterface, m_Parameters, "string", Engine::EPropertyType::String, "MaterialParameter", Engine::EPropertyType::Struct, Engine::MapAccessor<unordered_map<string, MaterialParameter>>::Get())
DECLARE_MAP_INFO(MaterialInterface, m_TextureSlots, "string", Engine::EPropertyType::String, "TextureSlot", Engine::EPropertyType::Struct, Engine::MapAccessor<unordered_map<string, TextureSlot>>::Get())
BEGIN_PROPERTIES(MaterialInterface)
	REFLECT_PROPERTY(MaterialInterface, m_BlendMode, "EBlendMode", Engine::EPropertyType::Enum, MaterialInterface_m_BlendMode_Meta)
	REFLECT_PROPERTY(MaterialInterface, m_CullMode, "ECullMode", Engine::EPropertyType::Enum, MaterialInterface_m_CullMode_Meta)
	REFLECT_PROPERTY(MaterialInterface, m_FillMode, "EFillMode", Engine::EPropertyType::Enum, MaterialInterface_m_FillMode_Meta)
	REFLECT_PROPERTY(MaterialInterface, m_DepthMode, "EDepthMode", Engine::EPropertyType::Enum, MaterialInterface_m_DepthMode_Meta)
	REFLECT_PROPERTY(MaterialInterface, m_DepthCompareOp, "ECompareOp", Engine::EPropertyType::Enum, MaterialInterface_m_DepthCompareOp_Meta)
	REFLECT_PROPERTY(MaterialInterface, m_VertexShader, "Shader", Engine::EPropertyType::Object, {})
	REFLECT_PROPERTY(MaterialInterface, m_PixelShader, "Shader", Engine::EPropertyType::Object, {})
	REFLECT_CONTAINER_PROPERTY(MaterialInterface, m_Parameters, "unordered_map<string, MaterialParameter>", Engine::EPropertyType::Map, &MaterialInterface_m_Parameters_ContainerData, {})
	REFLECT_CONTAINER_PROPERTY(MaterialInterface, m_TextureSlots, "unordered_map<string, TextureSlot>", Engine::EPropertyType::Map, &MaterialInterface_m_TextureSlots_ContainerData, {})
END_PROPERTIES

EMPTY_FUNCTIONS(MaterialInterface)

IMPLEMENT_CLASS(MaterialInterface, Resource)

#pragma endregion // CLASS: MaterialInterface

#pragma region CLASS: Mesh
BEGIN_METADATA(Mesh, m_Topology)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(Mesh, m_VertexCount)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(Mesh, m_IndexCount)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(Mesh, m_BoundingBoxMin)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(Mesh, m_BoundingBoxMax)
	CATEGORY(L"PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_PROPERTIES(Mesh)
	REFLECT_PROPERTY(Mesh, m_Topology, "ETopology", Engine::EPropertyType::Enum, Mesh_m_Topology_Meta)
	REFLECT_PROPERTY(Mesh, m_VertexCount, "uint32", Engine::EPropertyType::UInt32, Mesh_m_VertexCount_Meta)
	REFLECT_PROPERTY(Mesh, m_IndexCount, "uint32", Engine::EPropertyType::UInt32, Mesh_m_IndexCount_Meta)
	REFLECT_PROPERTY(Mesh, m_BoundingBoxMin, "vec3", Engine::EPropertyType::Vector3, Mesh_m_BoundingBoxMin_Meta)
	REFLECT_PROPERTY(Mesh, m_BoundingBoxMax, "vec3", Engine::EPropertyType::Vector3, Mesh_m_BoundingBoxMax_Meta)
END_PROPERTIES

EMPTY_FUNCTIONS(Mesh)

IMPLEMENT_CLASS(Mesh, Resource)

#pragma endregion // CLASS: Mesh

#pragma region CLASS: Model
DECLARE_CONTAINER_INFO(Model, m_Materials, "Material*", Engine::EPropertyType::Object, Engine::LinearContainerAccessor<vector<Material*>, Material*>::Get())
DECLARE_CONTAINER_INFO(Model, m_Meshes, "Mesh*", Engine::EPropertyType::Object, Engine::LinearContainerAccessor<vector<Mesh*>, Mesh*>::Get())
BEGIN_PROPERTIES(Model)
	REFLECT_CONTAINER_PROPERTY(Model, m_Materials, "vector<Material*>", Engine::EPropertyType::Array, &Model_m_Materials_ContainerData, {})
	REFLECT_CONTAINER_PROPERTY(Model, m_Meshes, "vector<Mesh*>", Engine::EPropertyType::Array, &Model_m_Meshes_ContainerData, {})
	REFLECT_PROPERTY(Model, m_Skeleton, "Skeleton", Engine::EPropertyType::Object, {})
END_PROPERTIES

EMPTY_FUNCTIONS(Model)

IMPLEMENT_CLASS(Model, Resource)

#pragma endregion // CLASS: Model

#pragma region CLASS: Skeleton
DECLARE_CONTAINER_INFO(Skeleton, m_Bones, "Bone", Engine::EPropertyType::Struct, Engine::LinearContainerAccessor<vector<Bone>, Bone>::Get())
DECLARE_MAP_INFO(Skeleton, m_BoneMap, "wstring", Engine::EPropertyType::Wstring, "uint32", Engine::EPropertyType::UInt32, Engine::MapAccessor<unordered_map<wstring, uint32>>::Get())
BEGIN_PROPERTIES(Skeleton)
	REFLECT_CONTAINER_PROPERTY(Skeleton, m_Bones, "vector<Bone>", Engine::EPropertyType::Array, &Skeleton_m_Bones_ContainerData, {})
	REFLECT_CONTAINER_PROPERTY(Skeleton, m_BoneMap, "unordered_map<wstring, uint32>", Engine::EPropertyType::Map, &Skeleton_m_BoneMap_ContainerData, {})
END_PROPERTIES

EMPTY_FUNCTIONS(Skeleton)

IMPLEMENT_CLASS(Skeleton, Resource)

#pragma endregion // CLASS: Skeleton

#pragma region CLASS: Resource
BEGIN_METADATA(Resource, m_Version)
	READONLY
END_METADATA

BEGIN_PROPERTIES(Resource)
	REFLECT_PROPERTY(Resource, m_Tag, "wstring", Engine::EPropertyType::Wstring, {})
	REFLECT_PROPERTY(Resource, m_Version, "uint32", Engine::EPropertyType::UInt32, Resource_m_Version_Meta)
END_PROPERTIES

EMPTY_FUNCTIONS(Resource)

IMPLEMENT_CLASS(Resource, Base)

#pragma endregion // CLASS: Resource

#pragma region CLASS: Shader
BEGIN_PROPERTIES(Shader)
	REFLECT_PROPERTY(Shader, m_RHIShader, "RHIShader", Engine::EPropertyType::Object, {})
END_PROPERTIES

EMPTY_FUNCTIONS(Shader)

IMPLEMENT_CLASS(Shader, Resource)

#pragma endregion // CLASS: Shader

#pragma region CLASS: Sprite
BEGIN_METADATA(Sprite, m_Pivot)
	DEFAULT(vec2(0.5f, 0.5f))
END_METADATA

BEGIN_PROPERTIES(Sprite)
	REFLECT_PROPERTY(Sprite, m_Texture, "Texture", Engine::EPropertyType::Object, {})
	REFLECT_PROPERTY(Sprite, m_Region, "Rect", Engine::EPropertyType::Struct, {})
	REFLECT_PROPERTY(Sprite, m_Pivot, "vec2", Engine::EPropertyType::Vector2, Sprite_m_Pivot_Meta)
END_PROPERTIES

EMPTY_FUNCTIONS(Sprite)

IMPLEMENT_CLASS(Sprite, Resource)

#pragma endregion // CLASS: Sprite

#pragma region CLASS: Texture
BEGIN_METADATA(Texture, m_Path)
	DIRECTORY
	READONLY
END_METADATA

BEGIN_PROPERTIES(Texture)
	REFLECT_PROPERTY(Texture, m_PixelPerUnit, "f32", Engine::EPropertyType::F32, {})
	REFLECT_PROPERTY(Texture, m_Path, "wstring", Engine::EPropertyType::Wstring, Texture_m_Path_Meta)
END_PROPERTIES

EMPTY_FUNCTIONS(Texture)

IMPLEMENT_CLASS(Texture, Resource)

#pragma endregion // CLASS: Texture

#pragma region CLASS: Button
EMPTY_PROPERTIES(Button)

EMPTY_FUNCTIONS(Button)

IMPLEMENT_CLASS(Button, UIComponent)

#pragma endregion // CLASS: Button

#pragma region CLASS: UIComponent
EMPTY_PROPERTIES(UIComponent)

EMPTY_FUNCTIONS(UIComponent)

IMPLEMENT_CLASS(UIComponent, Component)

#pragma endregion // CLASS: UIComponent

#pragma region CLASS: GameObject
BEGIN_METADATA(GameObject, m_ID)
	CATEGORY("PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(GameObject, m_Index)
	CATEGORY("PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(GameObject, m_LayerIndex)
	CATEGORY("PROP_INFORMATION")
	READONLY
END_METADATA

BEGIN_METADATA(GameObject, m_TagSet)
	"PROP_TAGS"
END_METADATA

DECLARE_CONTAINER_INFO(GameObject, m_TagSet, "wstring", Engine::EPropertyType::Wstring, Engine::SetAccessor<unordered_set<wstring>, wstring>::Get())
BEGIN_METADATA(GameObject, m_Name)
	"PROP_NAME"
END_METADATA

BEGIN_METADATA(GameObject, m_Flags)
	"PROP_BITFLAG"
END_METADATA

BEGIN_PROPERTIES(GameObject)
	REFLECT_PROPERTY(GameObject, m_ID, "uint64", Engine::EPropertyType::UInt64, GameObject_m_ID_Meta)
	REFLECT_PROPERTY(GameObject, m_Index, "uint32", Engine::EPropertyType::UInt32, GameObject_m_Index_Meta)
	REFLECT_PROPERTY(GameObject, m_LayerIndex, "uint32", Engine::EPropertyType::UInt32, GameObject_m_LayerIndex_Meta)
	REFLECT_CONTAINER_PROPERTY(GameObject, m_TagSet, "unordered_set<wstring>", Engine::EPropertyType::Set, &GameObject_m_TagSet_ContainerData, GameObject_m_TagSet_Meta)
	REFLECT_PROPERTY(GameObject, m_Name, "wstring", Engine::EPropertyType::Wstring, GameObject_m_Name_Meta)
	REFLECT_PROPERTY(GameObject, m_Flags, "EObjectFlag", Engine::EPropertyType::Enum, GameObject_m_Flags_Meta)
END_PROPERTIES

EMPTY_FUNCTIONS(GameObject)

IMPLEMENT_CLASS(GameObject, Base)

#pragma endregion // CLASS: GameObject


#pragma endregion

#pragma pop_macro("new")

} // namespace Engine
