from model import ReflectedEnum, ReflectedType

from .enum_emitter import emit_enum_reflection
from .type_emitter import emit_type_reflection


def emit_generated_file(
    included_headers: list[str],
    reflected_enums: list[ReflectedEnum],
    reflected_types: list[ReflectedType],
    bitflag_enums: set[str],
) -> str:
    headers_code = "\n".join(f'#include "{header}"' for header in sorted(included_headers))
    enum_code = "\n".join(emit_enum_reflection(reflected_enum) for reflected_enum in reflected_enums)
    type_code = "\n".join(
        emit_type_reflection(reflected_type, bitflag_enums)
        for reflected_type in reflected_types
    )

    return f"""// Auto-generated by ReflectionTool
#include "Core/Public/Engine_Includes.h"
#include "Core/Reflection/Public/ReflectionMacro.h"
#include "Core/Reflection/Public/ReflectionContainers.h"

// [Header Includes]
{headers_code}

#pragma push_macro("new")
#undef new

// ==========================================================
// [ENUM REFLECTIONS]
// ==========================================================
#pragma region EnumReflections
{enum_code}
#pragma endregion

// ==========================================================
// [CLASS/STRUCT REFLECTIONS]
// ==========================================================
#pragma region ClassStructReflections
{type_code}
#pragma endregion

#pragma pop_macro("new")
"""